/* Hover dictionary for "The Night Train to Orvo".
   Rule for what goes in: a word or phrase a Korean middle-school student has probably not met,
   or a British / railway use of a word they know. Check new story text with: python wordlist.py adventure/orvo
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = the name of an object only (never underlined in text); flag 2 = underline the listed forms but not the bare headword */
window.GLOSS = [
  /* --- the railway --- */
  ['junction', 'a station where two or more railway lines meet', '(철도) 분기역, 환승역'],
  ['platform', 'the place in a station where you get on and off a train', '승강장'],
  ['guard', 'the person who is in charge of a train (British)', '(열차의) 차장'],
  ['assistant', 'a person who helps somebody with their job', '조수'],
  ['buffet', 'a small restaurant in a station (say "boo-fay")', '(역의) 간이식당'],
  ['waiting room', 'a room in a station where people sit until their train comes', '대합실'],
  ['carriage', 'one of the long parts of a train; it is pulled by the engine', '객차, 열차의 한 칸', 'carriages'],
  ['engine', 'the front part of a train, which pulls the rest', '기관차'],
  ['mail van', 'the carriage that carries the letters and parcels', '우편차'],
  ['guard\'s van', 'the carriage where the guard rides', '차장차'],
  ['dining car', 'the carriage where passengers eat', '식당차'],
  ['sleeping car', 'a carriage with beds in it', '침대차'],
  ['kitchen car', 'the carriage where the food is cooked', '주방차'],
  ['mail', 'letters and parcels that are sent by post', '우편물'],
  ['parcels', 'things that are wrapped up and sent by post', '소포', 'parcel'],
  ['track', 'the two metal rails that a train runs on', '선로'],
  ['signal', 'a light or an arm beside the track; it tells the train to stop or go', '신호기', 'signals'],
  ['signal arm', 'the long flat part of an old railway signal; it moves down to say "go"', '신호기의 팔 (완목)'],
  ['lever', 'a long handle that you pull to work a machine', '레버, 손잡이 막대'],
  ['whistles', 'makes a high, loud sound', '기적을 울리다', 'whistle|whistled'],
  ['timetable', 'a list of the times when trains leave and arrive', '(열차) 시간표', 'timetables'],
  ['passengers', 'people who are travelling on a train, a bus or a plane', '승객', 'passenger'],
  ['berth', 'a bed on a train or a ship', '(열차·배의) 침대', 'berths'],
  ['night call', 'a knock on your door to wake you up in the night', '야간 기상 호출', 'night calls'],
  ['punch', 'a tool that makes holes in paper; (as a verb) to make a hole with it', '펀치 (구멍 뚫는 도구); 구멍을 뚫다', 'punches|punched'],
  ['the end of the line', 'the last station; the railway stops here', '종착역'],

  /* --- telling the time --- */
  ['a quarter to', 'fifteen minutes before the hour. "A quarter to nine" is 8.45', '~시 15분 전 (a quarter to nine = 8시 45분)'],
  ['a quarter past', 'fifteen minutes after the hour. "A quarter past nine" is 9.15', '~시 15분 (a quarter past nine = 9시 15분)'],
  ['half past', 'thirty minutes after the hour. "Half past nine" is 9.30', '~시 반 (half past nine = 9시 30분)'],
  ['ten to twelve', 'ten minutes before twelve o\'clock: 11.50', '12시 10분 전 (11시 50분)'],
  ['twenty to midnight', 'twenty minutes before twelve o\'clock at night: 11.40 p.m.', '자정 20분 전 (밤 11시 40분)'],
  ['midnight', 'twelve o\'clock at night', '자정, 밤 12시'],
  ['on time', 'not early and not late', '정시에, 제시간에'],
  ['exactly', 'no more and no less', '정확히'],
  ['twice', 'two times', '두 번'],

  /* --- things people say and do --- */
  ['in the wrong order', 'not in the places where they should be, one after another', '순서가 틀린'],
  ['the right order', 'each one in the place where it should be', '올바른 순서'],
  ['is left', 'is still there when the others have gone', '남아 있다'],
  ['the very back', 'the back end; nothing is behind it', '맨 뒤'],
  ['drag', 'to pull something along while you hold it', '끌다, 끌어서 옮기다'],
  ['take hold of', 'to put your hand round something', '~을 잡다'],
  ['further away', 'more far away', '더 멀리', 'further'],
  ['brass', 'a bright yellow metal', '놋쇠, 황동'],
  ['handle', 'the part of a thing that you hold in your hand', '손잡이'],
  ['rides', 'travels in', '~을 타고 가다', 'ride'],
  ['gets off', 'leaves a train or a bus', '(탈것에서) 내리다', 'get off'],
  ['car', 'here: a railway carriage, not a motor car', '(여기서는) 열차의 객차', 'end of the car', 2],
  ['right-hand', 'on the right side', '오른쪽의'],
  ['smells of', 'has the smell of', '~ 냄새가 나다'],
  ['now and then', 'sometimes', '가끔, 이따금'],
  ['awake', 'not sleeping', '깨어 있는'],
  ['shade', 'the cover over a lamp', '전등갓'],
  ['go down', '(of lamps) become less bright', '(불빛이) 어두워지다'],
  ['meant', 'showed; told you (past of "mean")', '~을 뜻했다'],
  ['slides open', 'opens by moving to the side', '옆으로 밀려 열리다'],
  ['pleased with', 'happy about', '~에 만족한'],
  ['stove', 'a metal box with a fire inside; it keeps a room warm', '난로'],
  ['goes on', 'does not stop here; travels further', '(멈추지 않고) 계속 가다'],
  ['greetings', 'a friendly hello that you send to somebody', '인사, 안부'],
  ['snoring', 'breathing noisily while asleep', '코를 고는', 'snore|snores'],
  ['blinds', 'covers that you pull down over a window', '블라인드, 가리개'],
  ['bars', 'long thin pieces of metal across a window', '창살'],
  ['tablecloths', 'cloths that cover tables', '식탁보', 'tablecloth'],
  ['supper', 'a meal that you eat late in the evening', '늦은 저녁 식사'],
  ['luggage', 'the bags and cases that you take on a journey', '짐, 수하물'],
  ['lying down', 'resting on a bed or on the floor', '누워 있는'],
  ['climbing', 'going up', '올라가는', 'climbs|climbed'],
  ['coal smoke', 'smoke from burning coal, the hard black stuff that steam engines burn', '석탄 연기'],
  ['argue', 'to say angrily that you do not agree', '따지다, 말다툼하다'],
  ['tiers', 'levels, one on top of another', '(케이크의) 단, 층', 'tier'],
  ['gets married', 'becomes a wife or a husband', '결혼하다'],
  ['all the way to', 'the whole way to; not getting off before', '~까지 끝까지'],
  ['stowaway', 'a person (or an animal) that hides on a train or a ship to travel without a ticket', '몰래 탄 무임승객, 밀항자'],
  ['slippers', 'soft shoes that you wear indoors', '실내화, 슬리퍼'],
  ['a pile of', 'a lot of things lying one on top of another', '~ 더미'],
  ['knocked', 'hit the door with your hand, so that somebody inside can hear', '(문을) 두드렸다', 'knock|knocks'],
  ['tears up', 'pulls a piece of paper into small pieces', '찢어 버리다'],
  ['holds each ticket up to the lamp', 'lifts each ticket to the light so that he can see through the holes', '표를 하나씩 등불에 비춰 보다', 'held each ticket up to the lamp'],
  ['paw prints', 'the marks that an animal\'s feet leave', '(동물의) 발자국'],
  ['icicles', 'long thin pieces of ice that hang down', '고드름', 'icicle'],
  ['sledge', 'a thing for carrying people or goods over snow; it slides', '썰매'],
  ['postcard', 'a card with a picture on one side; you write on the other side and post it', '엽서'],

  /* --- things you can click in the scenes --- */
  ['water tower', 'a tall tank that holds water for steam engines', '급수탑', '', 0],
  ['signal box', 'the small building where the railway signals are worked', '신호소', '', 0],
  ['mail bag', 'a big, strong bag for carrying letters', '우편 자루', 'mail bags'],
  ['trolley', 'a flat cart with wheels, for moving luggage', '(짐) 수레', '', 0],
  ['lantern', 'a lamp with glass sides and a handle, for carrying', '등불, 랜턴', '', 0],
  ['lampshade', 'the cover over a lamp that makes the light soft', '전등갓', '', 0],
  ['curtain', 'a piece of cloth that hangs at a window', '커튼', '', 0],
  ['buffer stop', 'the strong fence at the end of a railway track', '(선로 끝의) 차막이', '', 0],
  ['chalet', 'a wooden house in the mountains, with a wide roof', '(알프스식) 오두막집', '', 0],
  ['peak', 'the pointed top of a mountain', '산봉우리', '', 0]
];
