/* Hover dictionary for "Where Is Gloria?".
   Rule for what goes in: a word or phrase a Korean middle-school student has probably not met,
   or a British / idiomatic use of a word they know. Check new story text with: python wordlist.py mystery/gloria
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = the name of an object only (never underlined in text); flag 2 = underline the listed forms but not the bare headword */
window.GLOSS = [
  /* --- the show --- */
  ['vegetable show', 'a village competition to see who has grown the biggest and best vegetables', '채소 품평회'],
  ['day off', 'a day when you do not have to work', '쉬는 날, 비번', 'day-off'],
  ['cake stall', 'a table where cakes are sold', '케이크 판매대'],
  ['badge', 'a small card or piece of metal that shows who you are', '배지, 신분증'],
  ['detective', 'a person whose job is to find out who did a crime', '탐정, 형사'],
  ['missing', 'not in its place; lost', '없어진, 사라진'],
  ['weighs', 'is this heavy', '무게가 ~이다'],
  ['weighed', 'put on a scale to find out how heavy it is; was this heavy', '무게를 쟀다; 무게가 ~였다'],
  ['kilos', 'kilograms', '킬로그램', 'kilo'],
  ['Show Secretary', 'the person who runs the show and writes everything down', '품평회 간사'],
  ['class', 'one part of a competition, for one kind of thing', '(대회의) 부문', 'Class 12|Class 3', 2],
  ['silver cup', 'a metal cup given to the winner', '은 우승컵'],
  ['first prize', 'what the winner gets', '1등상', 'first-prize'],
  ['second prize', 'what the person who comes second gets', '2등상'],
  ['come second', 'to finish one place behind the winner', '2등을 하다', 'has come second|have come second'],
  ['come first', 'to win', '1등을 하다'],
  ['programmes', 'thin books that tell you what will happen at a show (British spelling)', '행사 안내 책자', 'programme'],
  ['guarding', 'watching something so that nobody takes it or touches it', '지키고 있는'],
  ['check', 'a careful look to see that everything is right; to look in that way', '점검; 점검하다', 'checked'],
  ['tied shut', 'closed with a rope so that it will not open', '끈으로 묶어 닫은', 'tied both doors shut'],
  ['untied', 'opened by taking the rope off', '(끈을) 풀었다', 'untying'],
  ['corner', 'the part of a room where two walls meet', '구석'],
  ['in its place', 'where it should be', '제자리에'],
  ['not my business', 'nothing to do with me', '내가 상관할 일이 아닌'],
  ['row', 'a line of things side by side', '줄, 열'],
  ['one on top of the other', 'the first is lying on the second', '하나가 다른 하나 위에'],
  ['rules', 'what you must and must not do in a game or a competition', '규칙'],
  ['afterwards', 'later; after that', '나중에, 그 후에'],
  ['stole', 'took something that belongs to another person (past of "steal")', '훔쳤다', 'stolen'],
  ['planted', 'put a seed or a young plant into the ground', '심었다'],
  ['half past', 'thirty minutes after: half past nine is 9.30', '~시 반'],
  ['a quarter to', 'fifteen minutes before: a quarter to ten is 9.45', '~시 15분 전'],
  ['a quarter past', 'fifteen minutes after: a quarter past eleven is 11.15', '~시 15분'],
  ['twenty to twelve', '11.40', '11시 40분 (12시 20분 전)'],
  ['five to ten', '9.55', '9시 55분 (10시 5분 전)'],
  ['ten to twelve', '11.50', '11시 50분 (12시 10분 전)'],
  ['matter', 'are important', '중요하다', 'that matter', 2],

  /* --- things in the show tent --- */
  ['plank', 'a long, flat piece of wood', '널빤지', 'planks'],
  ['straw bales', 'big blocks of dry yellow grass, tied with string', '짚단', 'straw bale|bales|bale'],
  ['straw', 'the dry yellow stems of wheat; hats and baskets are made of it', '짚, 밀짚'],
  ['cloth', 'material made of cotton or wool; here, a piece of it that covers a table', '천; 식탁보'],
  ['lying', 'resting flat on the ground', '(바닥에) 놓여 있는'],
  ['scale', 'a machine that shows how heavy a thing is', '저울'],
  ['watering can', 'a pot with a long tube, for pouring water on plants', '물뿌리개'],
  ['tent pole', 'the tall post that holds a tent up', '천막 기둥'],
  ['wheelbarrow', 'a small cart with one wheel at the front and two handles; you push it', '외바퀴 손수레', 'wheelbarrows|barrow|barrows'],
  ['mud', 'soft, wet earth', '진흙'],
  ['scrap', 'a small piece torn from something bigger', '조각, 쪼가리', 'scraps'],
  ['boot prints', 'the marks that boots leave on soft ground', '장화 자국'],
  ['wheel mark', 'the line that a wheel leaves on the ground', '바퀴 자국', 'wheel marks'],
  ['label', 'a small piece of card that says what a thing is or whose it is', '라벨, 꼬리표'],
  ['tablecloth', 'a cloth that covers a table', '식탁보', 'tablecloths'],
  ['rosette', 'a prize made of ribbon, in the shape of a flower', '로제트 (리본으로 만든 상)'],
  ['hangs', 'is fixed at the top, with the bottom part free', '늘어져 있다'],
  ['lift', 'to move something up', '들어 올리다', 'lifted'],
  ['slope', 'a surface with one end higher than the other, like the side of a hill', '경사, 비탈'],
  ['rolled', 'moved by turning over and over, like a ball', '굴렸다; 굴렀다'],
  ['photograph', 'a photo', '사진', 'photographs'],
  ['handwriting', 'the way a person writes with a pen', '손글씨, 필체'],
  ['ink', 'the coloured liquid inside a pen', '잉크'],
  ['pleased with itself', 'proud of what it has done', '스스로 흐뭇해하는'],
  ['by hand', 'not with a machine', '손으로'],
  ['throw it away', 'put it in the bin because you do not want it', '버리다', 'throw away|throw that photograph away'],
  ['shakes her head', 'moves her head from side to side to say no', '고개를 젓다'],
  ['has been busy', 'has done a lot of things', '(누군가) 많은 일을 해 놓았다'],
  ['kept the door open', 'stopped the door from closing', '문이 닫히지 않게 했다', 'holding the door open'],
  ['nothing much', 'nothing interesting', '별것 아닌 것'],
  ['has room for', 'has space for', '~이 들어갈 자리가 있다'],

  /* --- the allotments --- */
  ['allotments', 'small pieces of land near a town or village; people pay a little money to grow vegetables there (British)', '주말농장, 시민 텃밭'],
  ['plot', 'a small piece of land for growing things', '(작은) 밭, 구획', 'plot 7', 2],
  ['gravel', 'very small stones, used to make paths', '자갈'],
  ['stepping stones', 'flat stones that you walk on, one after another', '디딤돌'],
  ['marker', 'a thing that shows where something is', '표시, 말'],
  ['fork', 'a place where one path becomes two', '갈림길'],
  ['scarecrow', 'a thing like a person, made of old clothes and straw, that keeps birds away from plants', '허수아비', 'scarecrows'],
  ['shed', 'a small wooden building for keeping tools in', '헛간, 창고', 'sheds'],
  ['pond', 'a small area of still water', '연못'],
  ['stream', 'a very small river', '시내, 개울'],
  ['hedge', 'a row of bushes that makes a kind of wall round a field or garden', '산울타리'],
  ['hens', 'female chickens', '암탉', 'hen'],
  ['cabbage', 'a round vegetable made of many large green leaves', '양배추', 'cabbages'],
  ['rhubarb', 'a plant with large leaves and long red stems that you can cook and eat', '루바브 (대황)'],
  ['hollow', 'a place that is lower than the ground round it, like a shallow bowl', '움푹 팬 곳'],
  ['moss', 'a very small, soft green plant that grows on wet stones and old roofs', '이끼'],
  ['squeaked', 'made a short, high sound, like a mouse', '삐걱거렸다', 'squeak|squeaks'],
  ['struck', '(of a clock) rang to tell the time (past of "strike")', '(시계가) 쳤다'],
  ['metre', 'a hundred centimetres (British spelling)', '미터'],
  ['as far as', 'to that place and no further', '~까지'],
  ['can\'t miss', 'cannot fail to see, because he is so easy to see', '못 보고 지나칠 수가 없다'],
  ['went off', 'went away', '(자리를) 떴다'],
  ['I lost it', 'I could not see it any more', '놓쳤다, 더는 안 보였다'],
  ['dear', 'a friendly word that some older people use when they talk to you', '(친근하게 부르는 말) 얘야, 자네'],
  ['oh dear', 'something you say when a thing is going wrong', '이런, 저런'],
  ['caught on', 'held by something, so that it cannot fall or blow away', '~에 걸린'],
  ['gate post', 'the strong post that a gate hangs on', '대문 기둥'],
  ['flat', 'pressed down; not standing up', '납작하게 눌린', 'is flat', 2],
  ['car park', 'a place where people leave their cars (British)', '주차장'],
  ['village hall', 'a building that everybody in a village can use for meetings and parties', '마을 회관'],
  ['goes by', 'passes', '지나가다'],
  ['compares', 'looks at two or more things to see how they are different', '비교하다', 'compare'],
  ['take a wrong turn', 'go the wrong way', '길을 잘못 들다'],
  ['the hard part', 'the difficult part', '어려운 부분'],
  ['is left', 'is still there when the others are taken away', '남아 있다'],
  ['looks as if', 'seems to you that', '~인 것처럼 보이다'],
  ['direction', 'the way that something goes or points', '방향'],
  ['put it away', 'put it back in the place where it is kept', '제자리에 넣어 두었다'],
  ['get across', 'get to the other side', '건너가다', 'got across'],
  ['a bit', 'a little', '약간'],

  /* --- the tea tent --- */
  ['queue', 'a line of people waiting for something (British)', '줄, 대기 행렬'],
  ['counter', 'the long table in a shop or cafe where you are served', '계산대, 판매대'],
  ['stove', 'a thing you cook on', '레인지, 화덕'],
  ['lid', 'the cover on top of a pot or a box', '뚜껑'],
  ['peel', 'the skin of a fruit or vegetable after it has been cut off', '(깎아 낸) 껍질'],
  ['saw', 'a tool with a long metal blade and sharp teeth, for cutting wood', '톱', 'a saw|the saw|borrowed saw', 2],
  ['chopping', 'cutting into small pieces with a knife', '(칼로) 썰고 있는'],
  ['fetch', 'to go and get something, and bring it back', '가서 가져오다', 'fetched'],
  ['Gran', 'grandmother (informal)', '할머니'],
  ['out of the way', 'in a place where nobody will fall over it', '방해되지 않는 곳에'],
  ['well done', 'what you say to somebody who has done something good', '잘했어'],
  ['borrow', 'to take something for a short time and then give it back', '빌리다', 'borrowed'],
  ['poor', 'you say this when you feel sorry for somebody', '가엾은', 'Poor Walter', 2],
  ['worried', 'afraid that something bad may happen', '걱정하는'],
  ['windy', 'with a lot of wind', '바람이 부는'],
  ['ran over', 'went over it with a wheel', '(바퀴로) 밟고 지나갔다'],
  ['sticky', 'like glue or honey: it stays on your fingers', '끈적끈적한'],
  ['pleased', 'happy about something', '기뻐하는'],
  ['beat', 'to do better than somebody in a game or competition', '이기다', 'beat him', 2],
  ['where is the fun in that', 'that would not be fun at all', '그게 무슨 재미가 있겠어'],
  ['mended', 'put back together after it was broken or torn', '고친, 다시 이어 붙인'],
  ['whole', 'all of it; not in pieces', '전체의; 온전한'],
  ['the wrong way up', 'with the top at the bottom or at the side', '거꾸로, 방향이 틀리게', 'the right way up'],
  ['drops into place', 'moves to the right place and stays there', '제자리에 딱 들어가다'],
  ['belong', 'to be in the right place', '제자리에 있다, 속하다'],
  ['pin', 'to fix something to a thing with a small sharp piece of metal', '핀으로 꽂다, 달다'],
  ['politely', 'in a kind and careful way', '공손하게'],
  ['wasp', 'a black and yellow insect that can sting', '말벌'],
  ['steam', 'the white cloud that comes from very hot water', '김, 수증기'],
  ['striped', 'with lines of different colours', '줄무늬의'],
  ['doorway', 'the opening where a door is', '출입구'],
  ['thick', '(of soup) not thin like water', '걸쭉한', 'thick orange soup', 2],
  ['enjoyed himself', 'had a good time', '즐거운 시간을 보냈다'],
  ['goes very white', 'loses the colour in his face, because he has had a shock', '얼굴이 하얗게 질리다'],
  ['the rest', 'the part that is left', '나머지'],
  ['one pound', 'British money: £1', '1파운드 (영국 화폐)'],
  ['bucket', 'an open container with a handle, for carrying water', '양동이'],
  ['stuck to', 'fixed to it, so that it does not fall off', '~에 달라붙은'],
  ['have you still got', 'do you still have (British)', '아직 가지고 있니'],
  ['over your shoulder', 'from just behind you', '어깨 너머로'],
  ['wherever', 'in any place that', '어디든지'],

  /* --- three o'clock --- */
  ['village green', 'the piece of grass in the middle of a village', '마을 잔디 광장'],
  ['band', 'a group of people who play music together', '악단', 'the band', 2],
  ['in one piece', 'whole; not cut up or broken', '온전한 상태로'],
  ['does not mind', 'is not unhappy about it', '개의치 않는다'],
  ['tastes', 'puts a little in his mouth to see what it is like', '맛을 보다'],
  ['at last', 'in the end, after a long time', '마침내'],
  ['envelope', 'the paper cover that you put a letter in', '봉투'],
  ['came back for more', 'liked it so much that they wanted some more', '(맛있어서) 또 먹으러 왔다'],
  ['in the soup', 'in trouble (an old saying). Today it is really true as well', '곤경에 처한 (관용 표현). 여기서는 글자 그대로의 뜻도 된다'],
  ['washing up', 'washing the cups and plates (British)', '설거지'],
  ['went wrong', 'did not work as she wanted', '잘못되었다'],

  /* --- things you can click in the scenes; some of them turn up in the story as well --- */
  ['pumpkin', 'a very big, round, orange vegetable', '호박', '', 0],
  ['seeds', 'the small hard parts of a plant; new plants grow from them', '씨앗', '', 0],
  ['flags', 'pieces of coloured cloth on a string or a stick', '깃발', '', 0],
  ['bridge', 'a thing built over water so that people can cross', '다리', '', 0],
  ['beehives', 'boxes that bees live in', '벌통', '', 0],
  ['compost heap', 'a pile of old leaves and vegetable peel; it slowly turns into food for plants', '퇴비 더미', '', 0],
  ['hen house', 'a small wooden house for chickens', '닭장', '', 0],
  ['greenhouse', 'a glass building for growing plants in', '온실', '', 0],
  ['apple trees', 'trees that apples grow on', '사과나무', '', 0],
  ['sunflowers', 'very tall plants with big yellow flowers', '해바라기', '', 0],
  ['beans', 'long green vegetables that grow on climbing plants', '콩 (덩굴강낭콩)', '', 0],
  ['blackboard', 'a dark board that you write on with chalk', '칠판', '', 0],
  ['ladle', 'a big, deep spoon with a long handle, for serving soup', '국자', '', 0],
  ['pot', 'a deep, round thing for cooking in', '냄비, 솥', '', 0],
  ['carrot cake', 'a sweet cake made with carrots', '당근 케이크', '', 0]
];
