/* Hover dictionary for "Answer All Questions".
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = a word the player has to find, or the name of a thing (never underlined in text);
   flag 2 = underline the listed forms but not the bare headword.
   Check new story text with: python wordlist.py cipher/exam */
window.GLOSS = [
  /* --- words the player has to find: the key box --- */
  ['honest', 'an honest person tells the truth and does not cheat or steal', '정직한', '', 0],
  ['whole / hole', 'whole = all of something. hole = an empty space in something', 'whole 전체의 / hole 구멍', '', 0],
  ['off / of', 'off = not working, or away from. of = belonging to (a cup of tea)', 'off 꺼진, 떨어져 / of ~의', '', 0],
  ['know / no', 'know = to have something in your head. no = the opposite of yes', 'know 알다 / no 아니, 없는', '', 0],
  ['accept / except', 'accept = to say yes to something. except = but not', 'accept 받아들이다 / except ~을 제외하고', '', 0],
  ['separate', 'not together; apart. Spelt with A in the middle: sep-A-rate', '따로 떨어진, 분리된 (철자 주의: sep-a-rate)', '', 0],
  ['there / their', 'there = in that place (there is, there are). their = belonging to them', 'there 거기에, ~이 있다 / their 그들의', '', 0],
  ['here / hear', 'here = in this place. hear = what you do with your ears', 'here 여기에 / hear 듣다', '', 0],
  ['hour / our', 'hour = sixty minutes. our = belonging to us', 'hour 한 시간 / our 우리의', '', 0],
  ['knew / new', 'knew = the past tense of know. new = not old', 'knew 알았다 / new 새로운', '', 0],
  ['affect / effect', 'affect (verb) = to change something or somebody. effect (noun) = the change itself, the result', 'affect 영향을 미치다 (동사) / effect 영향, 결과 (명사)', '', 0],
  ['some / sum', 'some = a number of. sum = what you get when you add numbers together', 'some 약간의 / sum 합계', '', 0],
  ['tomorrow', 'the day after today. One M, two Rs', '내일 (철자 주의: m 하나, r 둘)', '', 0],
  /* --- the copy-room door: one word changes into another --- */
  ['explanation', 'what you say to make something clear (from EXPLAIN; the noun has no I)', '설명 (explain의 명사형)', '', 0],
  ['choice', 'the chance to choose; the thing you choose (from CHOOSE)', '선택 (choose의 명사형)', '', 0],
  ['decision', 'what you have when you have decided (from DECIDE)', '결정 (decide의 명사형)', '', 0],
  ['knowledge', 'all the things that somebody knows (from KNOW)', '지식 (know의 명사형)', '', 0],
  ['behaviour', 'the way somebody behaves (from BEHAVE). America writes "behavior"', '행동, 품행 (behave의 명사형; 미국식 철자는 behavior)', '', 0],
  ['favourite', 'liked more than all the others (from FAVOUR). America writes "favorite"', '가장 좋아하는 (미국식 철자는 favorite)', '', 0],
  ['dishonest', 'not honest: a dishonest person lies, cheats or steals', '정직하지 못한 (honest의 반대말)', '', 0],
  ['impossible', 'not possible: it cannot be done', '불가능한 (possible의 반대말)', '', 0],
  ['disappearance', 'when somebody or something disappears (from DISAPPEAR)', '사라짐, 실종 (disappear의 명사형)', '', 0],
  ['suspicion', 'a feeling that something is wrong, or that somebody has done something bad (from SUSPECT)', '의심, 혐의 (suspect의 명사형)', '', 0],
  /* --- the page from the shredder --- */
  ['candidate', 'a person who is taking an exam, or trying to get a job', '수험생, 지원자', '', 0],
  ['successful', 'a successful person gets what he or she was trying for', '성공한, 합격한', '', 0],
  ['recognise', 'to know who or what something is, because you have seen or heard it before. America writes "recognize"', '알아보다 (미국식 철자는 recognize)', '', 0],
  ['strict', 'a strict rule must be obeyed exactly; a strict teacher makes sure that it is', '엄격한', '', 0],
  ['disgrace', 'when people think badly of you because of something you have done; the opposite of honour', '불명예, 망신', '', 0],
  ['abolished', 'ended by law, for ever', '(법·제도가) 폐지된', '', 0],
  /* --- the dictionary in the library --- */
  ['colour', 'red, blue and green are colours. America writes "color"', '색 (미국식 철자는 color)', '', 0],
  ['centre', 'the middle of something. America writes "center"', '중심, 가운데 (미국식 철자는 center)', '', 0],
  ['travelled', 'went from one place to another (the past of TRAVEL). America writes "traveled"', '여행했다, 이동했다 (미국식 철자는 traveled)', '', 0],
  ['grey', 'the colour between black and white. America writes "gray"', '회색 (미국식 철자는 gray)', '', 0],

  /* --- the names of things in the rooms --- */
  ['notice board', 'a board on a wall where people pin papers for others to read', '게시판', '', 0],
  ['armchair', 'a soft, comfortable chair with sides for your arms', '안락의자', '', 0],
  ['kettle', 'a thing for boiling water in', '주전자', '', 0],
  ['mug', 'a big cup with straight sides and no saucer', '머그잔', '', 0],
  ['fridge', 'a cold cupboard for keeping food and milk in', '냉장고', '', 0],
  ['blind', 'a cover that you pull down over a window', '블라인드', '', 0],
  ['biscuit tin', 'a metal box for keeping biscuits in', '비스킷 통', '', 0],
  ['locker', 'a small metal cupboard with a lock, where a pupil keeps things at school', '사물함', '', 0],
  ['fire extinguisher', 'a red metal bottle for putting out a small fire', '소화기', '', 0],
  ['radiator', 'a metal thing on a wall, full of hot water, that keeps a room warm', '라디에이터 (난방기)', '', 0],
  ['guillotine', 'here: a board with a long blade, for cutting paper straight', '(여기서는) 종이 재단기', '', 0],
  ['trolley', 'a small table on wheels, for moving heavy things', '손수레, 카트', '', 0],
  ['ream', 'a packet of 500 sheets of paper', '종이 한 묶음 (500장)', '', 0],
  ['globe', 'a ball with a map of the world on it', '지구본', '', 0],
  ['ladder', 'two long bars with steps between them, for climbing up', '사다리', '', 0],
  ['wall bars', 'wooden bars on the wall of a school hall, for climbing in PE lessons', '(체육관 벽의) 늑목', '', 0],
  ['stage', 'the high floor at one end of a hall, where people act or speak', '무대', '', 0],

  /* --- school words (British) --- */
  ['staffroom', 'the room in a school where the teachers sit when they are not teaching', '교무실, 교사 휴게실'],
  ['caretaker', 'the person whose job is to look after a school building: its keys, its heating, its repairs', '(학교·건물) 관리인'],
  ['site manager', 'the modern name for a school caretaker', '시설 관리인'],
  ['Head Teacher', 'the teacher who is in charge of a school', '교장', 'head teacher|the Head'],
  ['Head of English', 'the teacher who is in charge of all the English teachers', '영어과 부장 교사'],
  ['Examinations Officer', 'the teacher who looks after everything to do with exams', '시험 담당 교사'],
  ['department', 'here: all the teachers of one subject', '(여기서는) 교과부, 학과', 'departments|dept'],
  ['pupil', 'a child at school', '(초·중등학교) 학생', 'pupils'],
  ['Year 9', 'the school year for pupils of thirteen and fourteen, in England', '9학년 (만 13~14세, 한국의 중2쯤)'],
  ['examination', 'the long word for an exam', '시험', 'examinations'],
  ['sit an exam', 'to take an exam. In Britain you "sit" it', '시험을 치르다 (영국식 표현)', 'sits|sit the|sits the|sitting in front of|sit a|sitting the', 2],
  ['re-sit', 'to take an exam again', '재시험을 보다', 're-sits|re-sat'],
  ['mark', 'the number a teacher gives your work, to show how good it is', '점수', 'marks'],
  ['marked', 'a marked exam has been read by a teacher and given its mark', '채점된', 'marking'],
  ['marker', 'here: the person who reads an exam paper and gives it a mark', '(여기서는) 채점자'],
  ['marker pen', 'a thick pen for writing on boxes and boards', '마커펜'],
  ['exercise books', 'the thin books with lines that pupils write their school work in', '공책 (학교 과제용)'],
  ['revision cards', 'small cards with the things you must learn for an exam written on them', '시험 대비 암기 카드'],
  ['revising', 'learning things again before an exam', '시험공부(복습)하고 있는', 'revise|revision'],
  ['confiscated', 'taken away from somebody by a teacher, as a punishment', '압수된', 'confiscate|confiscation'],
  ['period', 'here: one lesson in the school day. Period three is the third lesson', '(여기서는) 교시', 'period three|period 3|period 5', 2],
  ['Maths', 'the British short word for Mathematics. America says "math"', '수학 (영국식 줄임말)', 'Mathematics'],
  ['timetable', 'the list that says which lesson is where, and when', '시간표'],
  ['set', 'here: a class of pupils who are all at about the same level in one subject', '(여기서는) 수준별 반', 'goes down a set', 2],
  ['excluded', 'sent away from a school for ever, as a punishment', '퇴학당한', 'thrown out of school|thrown out'],
  ['cancelled', 'stopped before it has happened', '취소된', 'cancel'],
  ['fire drill', 'a practice: the bell rings and everybody walks out of the building, as if there were a fire', '화재 대피 훈련', 'fire bell'],
  ['yard', 'the open ground beside a school, where pupils go at break', '(학교) 마당, 운동장'],
  ['visitors\' book', 'a book by the door where everybody who comes into a building writes a name and the time', '방문자 명부'],
  ['off sick', 'not at work, because you are ill', '아파서 결근한'],
  ['flu', 'an illness like a very bad cold, which keeps you in bed', '독감'],
  ['retires', 'stops working for ever, because of age', '은퇴하다', 'retire|retired'],
  ['conference', 'a big meeting that lasts a day or more', '회의, 학회'],
  ['bulletin', 'a short paper that gives the news of the week to a group of people', '(주간) 소식지, 회보', 'bulletins'],
  ['invigilating', 'watching pupils during an exam, to see that nobody cheats', '시험 감독을 하고 있는', 'invigilate'],
  ['PE kit', 'the clothes you wear for sport at school', '체육복'],
  ['set this exam', 'to set an exam is to write its questions', '시험 문제를 내다', 'set this exam|set the paper|sets', 2],

  /* --- the night --- */
  ['lock up', 'to lock all the doors of a building at the end of the day', '(건물) 문단속을 하다', 'locks up|locking up|locked up'],
  ['cupboard', 'a piece of furniture with doors and shelves, for keeping things in', '찬장, 수납장', 'cupboards'],
  ['shelf', 'a flat board in a cupboard or on a wall, for putting things on', '선반', 'shelves'],
  ['label', 'a small piece of paper or card on a thing, which says what it is', '라벨, 꼬리표', 'labels|labelled'],
  ['spare', 'extra; kept in case it is needed', '여분의, 예비의', 'spares'],
  ['hook', 'a bent piece of metal for hanging things on', '고리, 걸이', 'hooks'],
  ['key box', 'a small metal cupboard on a wall, where keys hang on hooks', '열쇠 보관함'],
  ['wheel', 'here: a small ring with letters on it, which you turn to open a lock', '(여기서는) 자물쇠의 글자 다이얼', 'wheels', 2],
  ['handle', 'the part of a door that you hold and push down to open it', '손잡이'],
  ['corridor', 'a long narrow way inside a building, with doors along it', '복도'],
  ['whistling', 'making a tune by blowing air through your lips', '휘파람을 불고 있는', 'whistle|whistles'],
  ['torch', 'a small electric light that you carry in your hand', '손전등'],
  ['red ring', 'a circle drawn round a mistake with a red pen', '(틀린 곳에 치는) 빨간 동그라미', 'red rings|ringed'],
  ['red pen', 'what a teacher corrects mistakes with', '(채점용) 빨간 펜'],
  ['spelt', 'written with these letters, in this order (the past of "spell")', '철자가 ~로 쓰인', 'spell|spells|spelling|spellings'],
  ['unpin', 'to take a paper down from a board by pulling out its pin', '핀을 뽑아 떼다', 'pinned|pin'],
  ['raw material', 'the plain stuff that you make something out of', '원료, 재료'],
  ['bolt', 'a metal bar that slides across to keep a door shut', '빗장, 볼트', 'bolts'],
  ['slots', 'long narrow holes', '(가늘고 긴) 구멍, 틈', 'slot'],
  ['buzzing', 'making a low sound like a bee, as a phone does when a message comes', '윙윙(진동)거리는', 'buzz|buzzes'],
  ['blurred', 'not clear; you cannot see the lines properly', '(사진이) 흐릿한'],
  ['legend', 'here (slang): somebody who has done something wonderful', '(속어) 전설적인 사람, 영웅'],
  ['photocopier', 'a machine that makes copies of pages', '복사기', 'copier'],
  ['copy room', 'the room in a school where the photocopier is', '복사실'],
  ['shredder', 'a machine that cuts paper into thin strips, so that nobody can read it', '문서 파쇄기', 'shred|shredded'],
  ['scraps', 'small pieces of paper, torn or cut off a bigger piece', '(종이) 조각, 쪼가리', 'scrap'],
  ['strips', 'long thin pieces', '길고 가는 조각', 'strip'],
  ['torn', 'pulled into pieces (the past of "tear")', '찢어진', 'tore|tear'],
  ['face down', 'with the printed side underneath, so that you cannot read it', '(인쇄면이) 아래로 가게, 엎어 놓은'],
  ['wastepaper bin', 'a small bin in a room, for paper that is not wanted', '휴지통'],
  ['recycling', 'the old paper that is collected to be made into new paper', '재활용 (폐지 수거)'],
  ['string', 'thin rope for tying things up', '끈'],
  ['pencil shavings', 'the thin curls of wood that come off a pencil when you sharpen it', '연필 깎은 부스러기'],
  ['telling tales', 'telling a teacher about the bad things that other pupils have done', '고자질하기'],
  ['worthless', 'worth nothing; no use to anybody', '쓸모없는, 가치 없는', 'worth nothing'],
  ['cheat', 'to do something that is not honest, in order to win or to pass', '부정행위를 하다', 'cheats|cheated|cheating'],
  ['copying', 'here: writing down what somebody else has written, and saying that it is your own', '(여기서는) 베끼기', 'copy from'],
  ['proof', 'something that shows that a thing is true', '증거'],
  ['draft', 'a first try at a piece of writing, before the finished one', '초안'],
  ['dictionary', 'a book that tells you what words mean and how they are spelt', '사전'],

  /* --- the page about the old exams --- */
  ['government', 'the people who run a country', '정부'],
  ['cell', 'a very small room with a lock, like a room in a prison', '독방, 작은 방', 'cells'],
  ['blanket', 'a thick warm cover for a bed', '담요'],
  ['matchbox', 'the tiny box that matches are sold in', '성냥갑'],
  ['collar', 'the part of a shirt that goes round your neck', '옷깃'],
  ['hem', 'the bottom edge of a shirt or a skirt', '옷단, 밑단'],
  ['handwriting', 'the way a person writes with a pen', '손글씨, 필체'],
  ['examiners', 'the people who set an exam and mark it', '시험관, 출제·채점자', 'examiner'],
  ['clerks', 'people whose job is to write and copy papers in an office', '서기, 사무원', 'clerk'],
  ['honour', 'something that makes people think well of you', '명예, 영광'],
  ['banned', 'not allowed to do something any more', '금지당한'],
  ['engineers', 'people who plan and build machines, roads and bridges', '기술자, 공학자'],
  ['poets', 'people who write poems', '시인'],
  ['searched', 'looked through somebody\'s clothes and bags for hidden things', '몸수색을 했다', 'search'],
  ['fought back', 'did something to stop the people who were hurting them', '맞서 싸웠다, 반격했다'],
  ['for life', 'for the rest of your life', '평생'],
  ['brick', 'a hard block of baked earth, for building walls', '벽돌'],
  ['system', 'a way of doing things that many people follow', '제도'],
  ['arrested', 'caught and taken away by the police', '체포된'],

  /* --- grammar words --- */
  ['noun', 'a word that is the name of a thing, a person or an idea: door, teacher, decision', '명사', 'nouns'],
  ['verb', 'a word for something that you do: decide, explain, know', '동사', 'verbs'],
  ['adjective', 'a word that describes a thing or a person: honest, grey, strict', '형용사'],
  ['adverb', 'a word that says how something is done: slowly, honestly', '부사'],
  ['prefix', 'letters that are put at the front of a word to change its meaning: UN-, DIS-, IM-', '접두사'],
  ['past tense', 'the form of a verb for things that have already happened: knew, went', '과거 시제'],
  ['describes', 'says what somebody or something is like', '묘사하다, 설명하다', 'describe'],
  ['capitals', 'the big letters: A, B, C', '대문자', 'capital letters'],
  ['initials', 'the first letters of somebody\'s names: J.A. for Jonah Ashby', '이름의 머리글자'],

  /* --- things, and ways of saying things --- */
  ['rubber band', 'a thin ring of rubber for holding things together', '고무줄'],
  ['yo-yo', 'a toy that goes up and down on a string', '요요'],
  ['dust', 'the grey powder that settles on things that nobody touches', '먼지'],
  ['crumbs', 'the tiny bits that are left when biscuits or bread have been eaten', '부스러기'],
  ['fence', 'a wall of wood or wire round a piece of ground', '울타리'],
  ['bicycle sheds', 'the small roofed place where pupils leave their bicycles', '자전거 보관소'],
  ['minibus', 'a small bus for about twelve people', '소형 버스, 승합차'],
  ['brass plate', 'a small flat piece of yellow metal with a word on it', '놋쇠 명판'],
  ['wired glass', 'strong glass with thin wire inside it', '철망 유리'],
  ['hockey stick', 'the long curved stick used for playing hockey', '하키 스틱'],
  ['sticker', 'a small picture or label that sticks to things', '스티커'],
  ['cardboard', 'thick stiff brown paper, used for making boxes', '판지, 골판지'],
  ['cardigan', 'a knitted jacket with buttons down the front', '카디건'],
  ['scarf', 'a long piece of cloth that you wear round your neck', '목도리'],
  ['lid', 'the top of a box or a tin, which you can take off', '뚜껑'],
  ['pocket', 'a small bag sewn into your clothes, for keeping things in', '주머니'],
  ['typewriter', 'an old machine with keys, for printing letters straight on to paper', '타자기'],
  ['ink', 'the coloured liquid inside a pen', '잉크'],
  ['mice', 'more than one mouse', '쥐들 (mouse의 복수)'],
  ['pudding', 'in Britain: the sweet dish at the end of a meal', '(영국) 후식'],
  ['paper jam', 'when a sheet of paper is stuck inside a machine', '종이 걸림'],
  ['ribbons', 'long thin strips', '리본처럼 길고 가는 조각'],
  ['tape', 'a strip of sticky clear plastic, for joining pieces of paper', '(접착) 테이프'],
  ['join', 'here: the place where two strips meet', '(여기서는) 이음매', 'joins', 2],
  ['lie flat', 'to stay down smoothly on a surface, and not curl up', '(들뜨지 않고) 평평하게 놓이다'],
  ['stuck', 'not able to move; fixed in its place', '끼인, 붙어 버린', 'stuck down'],
  ['stump', 'the short piece that is left when the rest has been used up', '(닳고 남은) 몽당'],
  ['Sphinx', 'in old stories, a monster that asked every traveller a question, and let nobody pass who could not answer it', '스핑크스 (수수께끼를 내는 괴물)'],
  ['Boston', 'a big city in the United States of America', '보스턴 (미국의 도시)'],
  ['Leeds', 'a big city in the north of England', '리즈 (잉글랜드 북부의 도시)'],
  ['compliment', 'something nice that is said about you', '칭찬'],
  ['a credit to', 'somebody who makes other people proud. "A credit to nobody" is a polite way of saying "very bad"', '~의 자랑거리 (a credit to nobody = 누구의 자랑도 못 되는)', 'credit to'],
  ['exceptions', 'people or things that a rule does not cover', '예외', 'exception'],
  ['security', 'keeping something safe', '보안'],
  ['doubts', 'feelings of not being sure that something is right', '의심, 의문', 'doubt'],
  ['on purpose', 'because you meant to; not by accident', '일부러, 고의로'],
  ['a great deal of', 'a lot of', '아주 많은'],
  ['no hard feelings', 'I am not angry with you', '나쁜 감정은 없어요'],
  ['none of your business', 'nothing to do with you; something you should not ask about', '네가 상관할 일이 아닌', 'no business of yours'],
  ['dare', 'to be brave enough to do something', '감히 ~하다'],
  ['supposed to', 'you are supposed to do something when people expect you to do it', '~하기로 되어 있는'],
  ['short of', 'not having enough of something', '~이 모자란'],
  ['sees to that', 'makes sure that it happens', '반드시 그렇게 되도록 챙기다'],
  ['for what it is worth', 'what I am going to say may not help much, but I will say it anyway', '도움이 될지는 모르겠지만'],
  ['in a hurry', 'quickly, because there is not much time', '서둘러'],
  ['gone cold', 'no longer warm', '식어 버린'],
  ['calm', 'quiet and not worried', '침착한, 태연한'],
  ['slam', 'to shut a door hard and noisily', '(문을) 쾅 닫다'],
  ['hums', 'makes a low, steady sound', '웅웅 소리를 내다'],
  ['pleasure', 'the feeling of being pleased', '기쁨, 만족'],
  ['managed', 'were able to do something difficult', '(어려운 일을) 해냈다'],
  ['ought to', 'should', '~해야 한다'],
  ['slip', 'a small piece of paper with something written on it', '쪽지, 전표'],
  ['tray', 'a flat open box for keeping or carrying things in', '쟁반, 서류함'],
  ['steel', 'a very strong grey metal', '강철'],
  ['pile', 'a number of things lying one on top of another', '더미'],
  ['flickers', 'goes on and off very quickly', '깜박거리다', 'flickered|flicker'],
  ['swings open', 'opens wide, turning on its side as a door does', '(문이) 활짝 열리다'],
  ['wrapped', 'covered all round with cloth or paper', '감싼, 두른'],
  ['wasted', 'used up, with nothing gained', '낭비된', 'waste'],
  ['per cent', 'out of every hundred: 31 per cent is 31 out of 100', '퍼센트'],
  ['passive', 'a piece of grammar: "the door was locked" is passive', '수동태'],
  ['item', 'one thing in a list', '물품, 항목'],
  ['destroy', 'to break something so completely that it is gone', '없애다, 파기하다'],
  ['borrowed', 'took something that belongs to somebody else, meaning to give it back', '빌려 갔다', 'borrow'],
  ['remind', 'to make somebody remember something', '상기시키다'],
  ['apart', 'away from each other', '서로 떨어져'],
  ['steals', 'takes something that belongs to somebody else, and keeps it', '훔치다', 'steal|stole|stolen'],
  ['whoever', 'the person who (when you do not know who it is)', '~한 사람이 누구든'],
  ['unless', 'if not', '~하지 않는 한'],
  ['mind', 'here: be careful with', '(여기서는) ~을 조심하다', 'mind your fingers', 2],
  ['belonged', 'was a part of something, or was the property of somebody', '~에 속했다, ~의 것이었다', 'belong|belongs|belonging to'],
  ['tied up', 'held together with string', '(끈으로) 묶인', 'tied'],
  ['ticking', 'making the small regular sound of a clock', '째깍거리는'],
  ['indeed', 'really; very much so', '정말로'],
  ['simply', 'just, and nothing more', '그냥, 단지'],
  ['addressed to', 'written for one person or one group of people', '~ 앞으로 쓴'],
  ['prize', 'something you are given for winning', '상'],
  ['feeding', 'giving food to', '먹이를 주고 있는'],
  ['fed', 'here: pushed something into a machine', '(여기서는) (기계에) 밀어 넣었다'],
  ['patience', 'being able to go on doing something slow or dull without getting cross', '인내심'],
  ['guards', 'people whose job is to watch a door or a gate', '경비병, 문지기'],
  ['versions', 'forms of the same thing that are a little different from each other', '(조금씩 다른) 판, 버전', 'version'],
  ['cheerful', 'happy, and showing it', '쾌활한, 기분 좋은']
];
