/* Hover dictionary for "Room 13 Is Not on the Plan".
   Rule for what goes in: a word or phrase a Korean middle-school student has probably not met,
   or a British / idiomatic use of a word they know. Check new story text with: python wordlist.py ghost/room13
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = the name of an object only (never underlined in text); flag 2 = underline the listed forms but not the bare headword */
window.GLOSS = [
  /* --- the hotel --- */
  ['lobby', 'the large room just inside the front door of a hotel', '(호텔) 로비'],
  ['night porter', 'a person who looks after a hotel and its guests at night', '(호텔) 야간 당직 직원', 'porter'],
  ['lift', 'a small moving room that carries people up and down inside a building (British); an elevator', '승강기, 엘리베이터 (영국식)', 'the lift|a lift', 2],
  ['plan', 'a drawing of a building from above, showing where every room is', '평면도', 'plans'],
  ['corridor', 'a long, narrow part of a building, with doors to the rooms on each side', '복도', 'corridors'],
  ['second floor', 'two floors above the street (British). Americans call it the third floor.', '3층 (영국식: 1층 위로 두 번째 층)'],
  ['guide', 'a small book that tells visitors what they need to know', '안내 책자'],
  ['booklet', 'a small, thin book', '소책자'],
  ['builder', 'a person or company that makes houses and other buildings', '건축업자', 'builders'],
  ['linen cupboard', 'a cupboard where clean sheets and towels are kept', '침구·수건 보관장'],
  ['register', 'the book in which a hotel writes the names of its guests', '숙박부'],
  ['pigeonhole', 'one of a set of small open boxes on a wall, for letters and keys', '(우편물·열쇠용) 칸막이 선반', 'pigeonholes'],
  ['notice', 'a piece of paper on a wall that tells people something', '안내문, 게시문'],
  ['frame', 'the wooden edge round a picture', '액자, 틀'],
  ['staff', 'the people who work in a place', '직원'],
  ['checked out', 'paid the bill and left the hotel', '체크아웃했다 (계산하고 호텔을 떠났다)'],
  ['permanent', 'staying for always, not just for a short time', '영구적인; (여기서는) 장기 투숙'],
  ['account', 'here: a hotel bill, the list of what a guest must pay', '계산서, 청구서'],
  ['no charge', 'free; there is nothing to pay', '무료'],
  ['kitchen boy', 'a boy who does the simple jobs in a hotel kitchen', '주방 심부름 소년'],
  ['answer', 'here: to go and see what somebody wants when they ring a bell', '(종소리에) 응답하다, 가 보다', 'answers|answered'],
  ['power cuts', 'times when the electricity stops', '정전', 'power cut'],
  ['torch', 'a small electric light you hold in your hand (British)', '손전등'],
  ['labels', 'small pieces of paper stuck on a thing to say what it is', '라벨, 이름표', 'label'],
  ['ink', 'the coloured liquid inside a pen', '잉크'],
  ['lever', 'a handle that you push or pull to make a machine work', '레버, 손잡이'],
  ['work the lift', 'make the lift go, by using its lever', '승강기를 작동시키다', 'works the lift|works the lever'],
  ['brass', 'a bright yellow metal', '놋쇠, 황동'],
  ['stamp', 'the small paper square you stick on a letter before you post it', '우표'],
  ['crossword', 'a word game: you fill squares with letters to make words', '십자말풀이'],
  ['handwriting', 'the way a person writes with a pen', '손글씨, 필체'],
  ['chalk', 'a soft white stick for writing on a board', '분필', 'chalked'],
  ['palm', 'a plant with long leaves, from hot countries', '야자나무'],

  /* --- cocoa --- */
  ['cocoa', 'a hot, sweet drink made with chocolate powder and milk', '코코아'],
  ['saucer', 'the small plate that goes under a cup', '(찻잔) 받침 접시'],
  ['tray', 'a flat piece of wood or metal for carrying cups and plates', '쟁반'],
  ['sugar lumps', 'small, hard squares of sugar', '각설탕', 'sugar lump|lumps|lump'],
  ['two sugars', 'two lumps (or spoons) of sugar in one drink', '설탕 두 개'],
  ['steaming', 'sending up steam, the white cloud that comes off something hot', '김이 나는'],

  /* --- the second floor --- */
  ['wallpaper', 'paper, often with a pattern, that is stuck on the walls of a room', '벽지'],
  ['papered over', 'covered with wallpaper so that it cannot be seen', '벽지로 덮어 가린'],
  ['draught', 'cold air that moves through a room or under a door (say "draft")', '외풍, 찬 바람'],
  ['pipes', 'tubes that carry water through a building', '수도관, 배관'],
  ['bulb', 'the glass part of an electric light', '전구', 'bulbs'],
  ['bare', 'with nothing covering it', '아무것도 덮이지 않은, 맨'],
  ['flickers', 'goes on and off very quickly', '깜박거리다', 'flicker|flickering'],
  ['fern', 'a green plant with leaves like feathers and no flowers', '양치식물 (고사리류)'],
  ['stand', 'a tall, narrow table made to hold one thing', '받침대', 'tall stand', 2],
  ['snoring', 'breathing noisily while asleep', '코를 고는'],
  ['breath', 'the air that comes out of your mouth', '입김, 숨'],
  ['keyhole', 'the hole in a lock where the key goes', '열쇠 구멍'],
  ['peeling', 'coming off in thin pieces', '(칠이) 벗겨지는'],
  ['pale', 'light in colour; not strong or bright', '옅은, 희미한'],
  ['crooked', 'not straight', '비뚤어진'],
  ['screw', 'a small metal thing like a nail; you turn it to fix one thing to another', '나사'],
  ['handle', 'the part of a door that you hold to open it', '손잡이'],
  ['strips', 'long, thin pieces', '길고 가는 조각', 'strip'],
  ['tear', 'to pull paper or cloth so that it comes apart (say "tair")', '찢다; 찢어지다'],
  ['loose', 'not fixed in its place; easy to pull off', '헐거운, 떨어지려 하는'],
  ['leaning', 'standing against something, not straight up', '기대어 있는'],
  ['disturb', 'to wake somebody, or to stop them when they are busy or resting', '방해하다'],
  ['except', 'but not; not counting', '~은 제외하고'],
  ['spot', 'a small place', '지점, 자리'],
  ['in case of fire', 'if there is a fire', '화재 시'],

  /* --- Room 13 --- */
  ['dust sheet', 'a large cloth put over furniture to keep the dust off', '먼지 막이 천', 'dust sheets'],
  ['sheet', 'a large piece of cloth (here, a dust sheet)', '천, 덮개', 'sheets'],
  ['armchair', 'a soft, comfortable chair with sides for your arms', '안락의자'],
  ['wardrobe', 'a tall cupboard for clothes', '옷장'],
  ['fireplace', 'the open place in a wall where a fire burns', '벽난로'],
  ['mantelpiece', 'the shelf above a fireplace', '벽난로 선반'],
  ['bell-pull', 'a long cord that you pull to ring a bell in another room', '호출용 종 줄'],
  ['tally marks', 'short lines that you draw to count things, in groups of five', '(다섯씩 묶어 세는) 획 표시'],
  ['floorboards', 'the long pieces of wood that make a floor', '마룻바닥 널'],
  ['cardigan', 'a knitted jacket that closes with buttons', '카디건'],
  ['swinging', 'moving from side to side while hanging', '흔들거리는'],
  ['rub', 'to move your hand over something again and again, pressing on it', '문지르다'],
  ['arithmetic', 'the part of maths that is about adding, taking away, multiplying and dividing', '산수'],
  ['exercise books', 'thin books with empty pages, for school work', '(학교) 공책', 'exercise book'],
  ['sum', 'a small piece of arithmetic, like 7 + 5', '(덧셈·뺄셈 같은) 계산 문제', 'sums'],
  ['marked', 'checked by a teacher, who shows which answers are right and which are wrong', '채점된'],
  ['tied up', 'held together with string', '(끈으로) 묶인'],
  ['pile', 'a number of things lying one on top of another', '더미'],
  ['string', 'very thin rope', '끈'],
  ['pupil', 'a child at school', '학생, 제자'],
  ['reach', 'to be able to touch something by holding out your arm', '(손이) 닿다'],
  ['slides', 'moves smoothly over a flat thing', '미끄러지듯 움직이다'],

  /* --- breakfast --- */
  ['nonsense', 'something that is silly or not true', '말도 안 되는 소리'],
  ['fountain pen', 'a pen that you fill with ink', '만년필'],
  ['pleased', 'happy about something', '기쁜, 만족스러운'],
  ['dared', 'been brave enough', '감히 ~했다'],

  /* --- how they talk --- */
  ['used to', 'did it, or was so, in the past, but not now', '(전에는) ~하곤 했다 / ~였다 (지금은 아님)', 'use to'],
  ['complains', 'says that it is not happy; here, the lift makes unhappy noises', '불평하다; (여기서는) 삐걱거리다'],
  ['came with the building', 'was already there when she bought it', '건물에 딸려 왔다 (원래부터 거기 있었다)'],
  ['set your watch by it', 'it always happens at exactly the same time', '(시계를 맞춰도 될 만큼) 늘 정확하다'],
  ['broke a rule', 'did something that the rules say you must not do', '규칙을 어겼다'],
  ['shut the room up', 'closed the room so that nobody could use it', '방을 폐쇄했다'],
  ['come off', 'are not stuck on any more', '(붙어 있던 것이) 떨어지다'],
  ['come unstuck', 'stopped being stuck on', '(붙어 있던 것이) 떨어지다'],
  ['come away from', 'is not stuck to it any more', '~에서 떨어지다'],
  ['patient', 'able to wait for a long time without getting angry', '참을성 있는'],
  ['shall', 'will (formal or old)', '~할 것이다 (격식체)'],
  ['no such', 'no ... like that', '그런 ~은 없다'],
  ['go without', 'to live without something that you usually have', '~없이 지내다'],
  ['in the end', 'after a long time; at last', '결국'],
  ['I can tell', 'I know it just by looking', '보면 안다'],
  ['been saving it', 'been keeping it for later', '아껴 두고 있었다'],
  ['by itself', 'with nobody touching it', '저절로'],
  ['let go of', 'stopped holding', '(잡고 있던 것을) 놓았다'],
  ['as if', 'in a way that makes it look like', '마치 ~인 것처럼'],
  ['straight at', 'directly at', '똑바로 ~을 향해'],
  ['straight through', 'directly through, with nothing to stop it', '그대로 뚫고'],
  ['not quite', 'not completely', '완전히는 ~아닌'],
  ['need never know', 'does not ever have to find out', '끝내 몰라도 된다'],
  ['take hold of', 'take it in your hand', '~을 (손으로) 잡다'],
  ['keep your hand still', 'do not move your hand', '손을 움직이지 않고 가만히 두다'],
  ['side by side', 'next to each other', '나란히'],
  ['turn the card over', 'turn it so that you can see the other side', '카드를 뒤집다'],
  ['white with cold', 'white because it is so cold', '추위로 하얗게 된'],
  ['nearly', 'almost', '거의'],
  ['opposite', 'on the other side of; across from', '~의 맞은편에'],
  ['ten past nine', 'ten minutes after nine o\'clock: 9.10', '9시 10분'],
  ['eight minutes past nine', 'eight minutes after nine o\'clock: 9.08', '9시 8분'],
  ['Go on, then', 'All right: do it', '자, 어서 해 봐'],
  ['a ring on it', 'a round mark on it', '둥근 자국이 나 있다'],
  ['rang', 'past of "ring" (ring, rang, rung)', '(종을) 울렸다 (ring의 과거형)', 'rung'],
  ['hung', 'put it up so that it hangs (past of "hang")', '걸었다 (hang의 과거형)'],
  ['lying', 'here: resting flat on something', '놓여 있는'],
  ['exactly', 'in every way; just', '정확히, 꼭'],
  ['ought to', 'should', '~해야 한다, ~일 것이다'],
  ['goes on', 'does not stop; continues', '계속 이어지다'],
  ['laid the tray', 'put the cup and everything else on the tray, ready to carry', '쟁반을 차렸다'],

  /* --- things you can click in the scenes --- */
  ['bell board', 'a board on the wall with a small bell for every room', '(방마다 종이 달린) 호출 표시판', '', 0],
  ['desk bell', 'a small bell on a desk; you hit the top to call somebody', '(탁자 위) 호출용 종', '', 0],
  ['fire extinguisher', 'a red metal bottle of water or foam for putting out a fire', '소화기', '', 0],
  ['screwdriver', 'a tool for turning screws', '드라이버 (나사돌리개)', '', 0],
  ['spectacles', 'glasses (an older word)', '안경', '', 0],
  ['marmalade', 'a kind of jam made from oranges', '마멀레이드 (오렌지 잼)', '', 0]
];
