/* Hover dictionary for "Seven Hours of Air".
   Rule for what goes in: a word or phrase a Korean middle-school student has probably not met,
   or a known word used in a ship / machine sense. Check new story text with: python wordlist.py scifi/air
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = the name of an object only (never underlined in text); flag 2 = underline the listed forms but not the bare headword */
window.GLOSS = [
  /* --- the station --- */
  ['Europa', 'one of the moons of Jupiter. It is covered in ice', '유로파 (얼음으로 덮인 목성의 위성)'],
  ['Jupiter', 'the largest planet that goes round our sun', '목성'],
  ['on board', 'on a ship or a station', '(배·우주선에) 타고 있는'],
  ['lander', 'a small spaceship that goes down to the ground and comes back up again', '착륙선'],
  ['Commander', 'the person in charge of a ship or a station', '선장, 지휘관'],
  ['cabin', 'a small room for sleeping in, on a ship or a station', '(배·우주선의) 선실', 'cabins'],
  ['corridor', 'a long narrow way inside a building, with doors along it', '복도'],
  ['spine', 'the line of bones down the middle of your back; here, the long corridor down the middle of the station', '척추; (여기서는) 한가운데를 지나는 긴 통로'],
  ['hatch', 'a small, strong door on a ship or a station', '해치 (우주선·배의 작고 튼튼한 문)', 'hatches'],
  ['hull', 'the outside body of a ship or a station', '선체 (배·우주선의 바깥 몸체)'],
  ['deck', 'one floor of a ship or a station', '(배·우주선의) 층, 갑판'],
  ['upper', 'higher; at the top', '위쪽의'],
  ['bow', 'the front end of a ship (it sounds like "now")', '선수 (배의 앞쪽)'],
  ['stern', 'the back end of a ship', '선미 (배의 뒤쪽)'],
  ['port', 'the left side of a ship, when you are looking towards the front', '좌현 (앞을 볼 때 배의 왼쪽)'],
  ['starboard', 'the right side of a ship, when you are looking towards the front', '우현 (앞을 볼 때 배의 오른쪽)'],
  ['galley', 'the kitchen of a ship or a station', '(배·우주선의) 주방'],
  ['med bay', 'the room where ill or hurt people are looked after', '의무실'],
  ['airlock', 'a small room with two doors, for going outside without letting the air out', '에어록 (공기가 새지 않게 드나드는 방)'],
  ['cold store', 'a very cold room for keeping food', '냉동 창고'],
  ['store', 'a room where things are kept until they are needed', '창고'],
  ['spares', 'extra parts that are kept for mending things', '예비 부품'],
  ['lab', 'a room for science work (short for "laboratory")', '실험실'],
  ['suit room', 'the room where the space suits are kept', '우주복 보관실'],
  ['suit', 'here: the special clothes you wear to go outside in space', '(여기서는) 우주복', 'suits'],
  ['plan', 'here: a drawing of a building seen from above, like a map', '(여기서는) 평면도, 배치도'],
  ['name plate', 'a small sign with a name written on it', '이름판, 명판'],
  ['wardrobe', 'a tall cupboard for clothes', '옷장'],
  ['ladder', 'two long bars with steps between them, for climbing up and down', '사다리'],
  ['ceiling', 'the top of a room, above your head', '천장'],
  ['zero gravity', 'when things have no weight and float about, as they do in space', '무중력'],
  ['gravity', 'the pull that makes things fall to the ground', '중력'],
  ['floating', 'staying up in the air, or on water, without falling', '(공중에) 떠 있는', 'float|floats|floated'],
  ['docks', '(of a spaceship) joins on to a station', '(우주선이) 도킹하다', 'docking'],

  /* --- air, pipes and handles --- */
  ['alarm', 'a loud sound or a warning that tells you something is wrong', '경보'],
  ['oxygen', 'the gas in the air that people need to breathe', '산소'],
  ['carbon dioxide', 'the gas that people breathe out', '이산화탄소'],
  ['pressure', 'how hard the air pushes on everything round it', '압력, 기압'],
  ['per cent', 'out of every hundred (%)', '퍼센트'],
  ['breath', 'the air that you take in and let out', '숨, 호흡'],
  ['gauge', 'a dial with a needle that shows how much of something there is (say "gayj")', '계기, 게이지', 'gauges'],
  ['needle', 'here: the thin pointer on a dial', '(여기서는) 계기의 바늘'],
  ['band', 'here: a strip of colour on a dial', '(여기서는) 색깔 띠'],
  ['seal', 'a soft ring round a door that stops air getting past', '밀폐 고무 (공기가 새지 않게 막는 테두리)'],
  ['safety valve', 'a valve that opens by itself when there is too much pressure', '안전밸브'],
  ['valve', 'a part that opens and shuts to let air or water through a pipe', '밸브'],
  ['pump', 'to push air or water along by moving a handle up and down; the thing you do it with', '펌프; 펌프질하다', 'pumping'],
  ['lever', 'a handle that you pull or push to work a machine', '레버 (당기거나 미는 손잡이)'],
  ['handle', 'the part of a thing that you hold in your hand', '손잡이', 'handles'],
  ['anticlockwise', 'round the opposite way to the hands of a clock', '시계 반대 방향으로'],
  ['steady', 'not moving and not changing', '변함없는, 일정한'],
  ['flashing', 'going on and off quickly', '깜박이는', 'flash'],
  ['buzzer', 'a thing that makes a short, ugly electric sound', '버저 (삑 하는 경고음 장치)'],
  ['reserve', 'something kept for the day when it is really needed', '예비용, 비상용'],
  ['tank', 'a large container for gas or water', '탱크, 저장통', 'tanks'],
  ['filter', 'a part that cleans air or water as it passes through', '필터, 여과기'],
  ['fault', 'something that has gone wrong in a machine', '고장, 결함'],
  ['pipe board', 'a board on the wall where the pipes can be turned', '배관 조절판'],
  ['pipe', 'a tube that carries water or gas', '관, 파이프', 'pipes'],
  ['tube', 'a long round container, open or shut at the ends', '관, 통, 튜브'],
  ['copper', 'a red-brown metal', '구리'],
  ['outlets', 'the places where something comes out', '배출구, 나가는 곳'],
  ['welded', 'joined by melting the metal, so that it can never move', '용접된'],
  ['joined', 'fixed together', '연결된', 'join'],
  ['loose ends', 'ends that are not joined to anything', '어디에도 연결되지 않은 끝', 'loose end'],
  ['waste', 'what nobody wants any more and is thrown away', '폐기물, 버리는 것'],
  ['patch', 'a piece of something that you stick over a hole', '(구멍을 막는) 덧댐 조각', 'patches'],
  ['kit', 'a set of tools or things for doing one job', '(도구) 세트'],
  ['chain', 'a line of metal rings joined together', '쇠사슬'],
  ['strip', 'a long narrow piece', '길고 가는 조각'],
  ['rising', 'going up', '올라가는'],
  ['shivers', 'shakes a little', '가늘게 떨다'],
  ['feed', 'here: to send air into', '(여기서는) 공기를 보내 주다'],
  ['runs', 'here: goes along from one place to another', '(여기서는) ~로 이어지다, ~를 따라 흐르다'],
  ['holds', 'keeps in one place; or, has room for', '붙잡아 두다; (얼마만큼) 담다'],

  /* --- electricity, and the garden --- */
  ['socket', 'the place in a wall where you plug in electric things', '콘센트'],
  ['plugged', 'joined to the electricity', '플러그를 꽂은', 'plugged in|plugged it in'],
  ['heater', 'a machine that makes a room warm', '난방기, 히터', 'heaters'],
  ['kettles', 'pots for boiling water', '주전자, 전기 포트'],
  ['toasters', 'machines that make slices of bread hot and brown', '토스터'],
  ['circuit', 'the path that electricity travels round', '(전기) 회로'],
  ['breaker', 'a safety switch that opens by itself when too much electricity is being used', '차단기 (두꺼비집 스위치)', 'breakers'],
  ['load', 'here: how much electricity is being used', '(여기서는) 전기 사용량'],
  ['limit', 'the most that is allowed', '한도'],
  ['rewired', 'given new electric wires', '전선을 새로 깐'],
  ['levels', 'how high or how strong something is set', '(밝기 등의) 단계'],
  ['algae', 'very small green water plants. With light, they make oxygen (say "AL-jee")', '조류 (물속의 아주 작은 녹색 식물)'],
  ['delicate', 'easy to hurt or to damage', '연약한'],
  ['hungriest', 'the most hungry', '가장 배고픈'],
  ['least', 'the smallest amount', '가장 적은'],
  ['twice', 'two times', '두 배; 두 번'],
  ['bubble', 'a small ball of air in water', '공기 방울', 'bubbles'],
  ['clipboard', 'a small board with a clip at the top, for holding papers', '클립보드 (집게 달린 서류판)'],
  ['log', 'the written record of what happens every day', '일지, 기록'],
  ['label', 'a small piece of paper on a thing that says what it is; (as a verb) to put a name on a thing', '라벨, 꼬리표; 이름표를 붙이다', 'labels|labelled'],
  ['glow', 'to give out a soft light', '은은하게 빛나다'],
  ['frame', 'bars that hold something up', '틀, 지지대'],
  ['shell', 'the hard cover of a sea animal', '조개껍데기'],
  ['dead', 'here: not working', '(여기서는) 꺼진, 작동하지 않는'],

  /* --- people and how they talk --- */
  ['polite', 'having good manners', '예의 바른'],
  ['allowed', 'able to do it because the rules say you may', '허락된'],
  ['may', 'be allowed to; or, will perhaps', '~해도 된다; ~일지도 모른다'],
  ['instructions', 'words that tell you how to do something', '사용법, 지시 사항'],
  ['describe', 'to say what something is like', '묘사하다, 설명하다', 'describing'],
  ['opposite', 'on the other side, facing it', '맞은편에'],
  ['directly', 'exactly; with nothing in between', '바로, 정확히'],
  ['beside', 'next to', '~의 옆에'],
  ['underneath', 'under it', '바로 아래에'],
  ['towards', 'in the direction of', '~쪽으로'],
  ['route', 'the way you go to get from one place to another', '경로, 가는 길'],
  ['unlock', 'to open a lock', '잠긴 것을 열다', 'unlocking'],
  ['jammed', 'stuck, so that it cannot move', '꽉 끼어 움직이지 않는'],
  ['shut', 'to close; closed', '닫다; 닫힌', 'shuts'],
  ['unusual', 'not what usually happens', '드문, 보기 드문'],
  ['silent', 'saying nothing', '아무 말이 없는'],
  ['calm', 'quiet, and not worried', '차분한'],
  ['ordered', 'asked a shop to send something', '주문했다'],
  ['private', 'belonging to one person, not to everybody', '개인의'],
  ['underlined', 'with a line drawn under it', '밑줄을 친'],
  ['noticed', 'saw it and knew that it was there', '알아차렸다'],
  ['reach', 'to get as far as; or, to speak to somebody by radio', '~에 이르다; ~와 연락이 닿다', 'reached|reaching'],
  ['rushes', 'moves very fast', '세차게 밀려들다'],
  ['drops', 'falls suddenly', '뚝 떨어지다'],
  ['settles', 'stops moving about and becomes still', '(흔들리다가) 가라앉다'],
  ['emptying', 'letting everything out until nothing is left', '(다) 비우는', 'empties'],
  ['incoming', 'coming in', '걸려 오는, 들어오는'],
  ['stuck', 'fixed there and not able to move; fixed on with glue or tape', '붙어 있는; 꼼짝 않는'],
  ['tied', 'fixed with string or with a strap', '묶인'],
  ['hung', 'put it up so that it hangs (past of "hang")', '걸어 놓았다', 'hangs'],
  ['pour', 'to make a drink run out of a bottle or a cup', '따르다, 붓다'],
  ['squeeze', 'to press something hard from both sides', '꽉 짜다'],
  ['cracks', 'thin lines where something has started to break', '갈라진 금'],
  ['ribbons', 'long thin pieces of cloth', '가늘고 긴 천 조각, 리본'],
  ['pouch', 'a small soft bag', '작은 주머니, 파우치'],
  ['holder', 'a thing that keeps something in its place', '꽂이, 홀더'],
  ['handwriting', 'the way one person writes with a pen', '손글씨'],
  ['capital letters', 'big letters: A, B, C, not a, b, c', '대문자'],
  ['pairs', 'sets of two things that go together', '켤레, 쌍'],
  ['peas', 'small round green vegetables', '완두콩'],
  ['ill', 'not well; sick', '아픈'],
  ['spare', 'extra; kept in case it is needed', '여분의, 예비의'],
  ['safety', 'being safe', '안전'],
  ['instead', 'in place of that', '그 대신에'],
  ['sum', 'a piece of adding or taking away with numbers', '(간단한) 계산'],
  ['sigh', 'a long, soft breath out', '한숨'],
  ['bump', 'a small knock that you can feel', '쿵 하고 부딪히는 느낌'],
  ['clunk', 'the short, heavy sound of metal stopping against metal', '철컹 하는 소리'],
  ['clack', 'a short, hard sound, like a big switch', '딸깍 하는 소리'],
  ['bang', 'a sudden loud noise', '쾅 하는 소리'],
  ['hiss', 'a long "sss" sound, like air coming out of a tyre', '쉬익 하는 소리', 'hisses|hissing'],
  ['screwdriver', 'a tool for turning screws', '드라이버'],
  ['supper', 'the evening meal', '저녁 식사'],
  ['incident', 'something bad or strange that has happened', '사고, 사건'],
  ['clues', 'things that help you to find an answer', '단서'],
  ['drag', 'to move a thing across the screen while you hold the mouse button down', '(마우스로) 끌다'],
  ['emergency', 'a sudden, dangerous time when people must act fast', '비상, 긴급 상황'],
  ['glue', 'sticky stuff for joining things together', '접착제, 풀'],
  ['slides', 'moves smoothly along', '미끄러지듯 움직이다'],
  ['single', 'only one', '단 하나의'],
  ['edge', 'the outside line of a thing', '가장자리'],
  ['marked', 'with these words written on it', '~라고 적힌'],
  ['ought to', 'should', '~해야 한다'],

  /* --- phrases --- */
  ['ten past two', '2.10', '2시 10분'],
  ['half past one', '1.30', '1시 30분'],
  ['eight minutes to two', '1.52', '2시 8분 전 (1시 52분)'],
  ['as soon as', 'at the moment when; not one second later', '~하자마자'],
  ['by hand', 'done by a person, not by a machine', '손으로, 수동으로'],
  ['half way', 'only half of the distance', '절반까지만'],
  ['straight back', 'back at once', '곧바로 다시'],
  ['lets go', 'stops holding', '놓다, 풀리다', 'let go'],
  ['in the way', 'in a place that stops you from getting past or from seeing', '(길이나 시야를) 가로막고 있는'],
  ['keep your eye on', 'watch it carefully', '~을 계속 지켜보다'],
  ['depends on', 'is different when that thing is different', '~에 따라 다르다'],
  ['would rather not', 'do not want to', '~하고 싶지 않다'],
  ['to spare', 'more than is needed', '남아도는, 여유분의'],
  ['cost you', 'made you lose', '(~을) 잃게 했다'],
  ['nowhere else', 'not to any other place', '다른 어느 곳에도 (보내지 말 것)'],
  ['sets off', 'begins a journey', '길을 떠나다'],
  ['live through', 'stay alive to the end of', '(힘든 시간을) 견디고 살아남다'],
  ['in a row', 'side by side, in a line', '한 줄로 나란히'],
  ['I have no idea', 'I do not know at all', '전혀 모르겠다'],
  ['no longer', 'not any more', '더 이상 ~않다'],
  ['of its own', 'that belongs only to it', '자기만의'],
  ['perfectly still', 'not moving at all', '전혀 움직이지 않는'],
  ['face to face', 'looking straight at each other', '서로 마주 보고'],
  ['rub it out', 'take the writing away', '지우다'],
  ['further off', 'a longer way away', '더 멀리서'],
  ['against rule 14', 'not allowed by rule 14', '규칙 14에 어긋나는'],

  /* --- things you can click in the scenes --- */
  ['sleeping bag', 'a warm bag that you sleep in', '침낭'],
  ['air vent', 'an opening in a wall where air comes into a room', '환기구'],
  ['porthole', 'a small round window in a ship', '둥근 창 (현창)', '', 0],
  ['locker', 'a small cupboard for your own things', '사물함', '', 0],
  ['fire extinguisher', 'a metal bottle of stuff for putting out a fire', '소화기', '', 0],
  ['tomato plant', 'the plant that tomatoes grow on', '토마토 나무', '', 0]
];
