/* Hover dictionary for "Forty Minutes of Dark".
   Rule for what goes in: a word or phrase a Korean middle-school student has probably not met,
   or a British / idiomatic use of a word they know. Check new story text with: python wordlist.py
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = the name of an object only (never underlined in text); flag 2 = underline the listed forms but not the bare headword */
window.GLOSS = [
  /* --- the case --- */
  ['chronometer', 'a very exact clock that ships used to find out where they were at sea', '크로노미터 (항해용 정밀 시계)', 'chronometers'],
  ['customs house', 'the building in a harbour where officers checked the goods coming off ships', '세관 건물'],
  ['harbour', 'a place on the coast where boats are kept safe from the sea', '항구', 'harbours'],
  ['for good', 'for ever', '영원히, 아주'],
  ['marine', 'of the sea and ships', '바다의, 선박의'],
  ['PC', 'short for "Police Constable", a British police officer', '순경 (Police Constable의 줄임말)'],
  ['constable', 'a police officer of the lowest rank (British)', '순경', 'constables'],
  ['curator', 'the person who looks after the things in a museum', '(박물관) 학예사'],
  ['caretaker', 'a person whose job is to look after a building', '건물 관리인'],
  ['staff', 'the people who work in a place', '직원'],
  ['witnesses', 'people who saw or heard what happened', '목격자', 'witness'],
  ['statement', 'what a person tells the police about what happened', '진술', 'statements'],
  ['timeline', 'a line of events in the order they happened', '시간순으로 늘어놓은 표'],
  ['obeys', 'does what a rule says', '(규칙을) 따르다', 'obey'],
  ['heap', 'an untidy pile', '(아무렇게나 쌓인) 더미'],
  ['edge', 'the outside line of a thing, where it ends', '가장자리'],
  ['suspect', 'to think that somebody may have done a crime', '의심하다'],
  ['blame', 'to say that somebody did the wrong thing', '탓하다, 책임을 묻다', 'blamed'],
  ['under arrest', 'held by the police', '체포된'],
  ['at the scene', 'at the place where the crime happened', '사건 현장에'],
  ['power cut', 'a time when the electricity stops', '정전'],
  ['persons', 'people (a formal police word)', '사람들 (격식체)'],
  ['missing', 'not in its place; lost', '없어진, 사라진'],
  ['Chart Room', 'the room where the sea maps are kept', '해도실 (바다 지도를 두는 방)'],
  ['chart', 'a map of the sea', '해도 (바다 지도)', 'charts'],
  ['cellar', 'a room under a house, used for keeping things', '지하 저장실', 'cellars'],
  ['ground floor', 'the floor of a building at street level (British)', '1층'],
  ['crate', 'a big wooden box for moving things', '나무 상자', 'crates'],
  ['fuse box', 'the box that holds the fuses for a building', '두꺼비집, 퓨즈함'],
  ['fuse', 'a small safety part in an electric system; it breaks if there is too much power', '퓨즈', 'fuses'],
  ['basement', 'the part of a building that is under the ground', '지하층'],
  ['store', 'a place where things are kept and not shown', '보관소, 창고', 'stores'],
  ['on show', 'in a place where visitors can see it', '전시 중인'],
  ['collect', 'to come and take something away', '가지러 오다, 수거하다'],
  ['catalogue', 'a list of all the things in a collection', '목록'],
  ['label', 'a small piece of paper that says what a thing is; (as a verb) to put a name on something', '라벨, 꼬리표; 이름표를 붙이다', 'labels|labelled'],
  ['sheet of labels', 'a piece of paper with labels on it', '라벨이 붙은 종이 한 장'],
  ['paperwork', 'the forms and letters that have to be finished', '서류 작업'],
  ['hand in', 'to give something back to the person in charge', '반납하다', 'hand them in'],
  ['sealed', 'closed so that nobody can open it without breaking something', '봉인된', 'seal|seals'],
  ['property', 'a thing that belongs to somebody', '소유물, 재산'],
  ['recovered', 'found and got back', '되찾은'],
  ['theft', 'the crime of stealing', '절도'],
  ['charged', 'told officially by the police: you did this crime', '기소된', 'charge|charges'],
  ['pounds', 'British money (£)', '파운드 (영국 화폐)'],
  ['dated', 'with this date written on it', '~일자의'],
  ['signed', 'with a name written at the end', '서명된'],
  ['Yours sincerely', 'the polite way to end a formal letter', '(편지 끝인사) 올림'],
  ['exceptions', 'people or times that a rule is not for', '예외', 'exception'],
  ['exists', 'is; is real', '존재하다', 'exist|existed'],

  /* --- clocks and sounds --- */
  ['tick', 'the short, light sound of a small clock or a watch', '(시계의) 째깍 소리', 'ticks|ticking|ticked'],
  ['tock', 'the slower, deeper sound of a big clock', '(큰 시계의) 똑딱 소리'],
  ['hiss', 'a long "sss" sound, like steam from a kettle or an angry cat', '쉬익 하는 소리', 'hisses|hissing'],
  ['creak', 'the long, complaining sound of old wood when you step on it', '삐걱거리는 소리', 'creaks|creaking|creaked'],
  ['drip', 'water falling one drop at a time; the sound it makes', '똑똑 떨어지는 물방울', 'drips|dripping'],
  ['hum', 'a low, steady sound, like a fridge or an electric wire', '윙윙거리는 낮은 소리', 'hums|humming'],
  ['ding', 'the short, bright sound of a small bell', '땡 하는 종소리'],
  ['chink', 'the light ringing sound of small metal things touching', '짤랑 (작은 금속 소리)'],
  ['clink', 'a short, light sound of metal on metal', '쨍그랑 (금속 소리)'],
  ['bang', 'a sudden loud noise', '쾅 하는 소리'],
  ['rattles', 'shakes and makes short, hard sounds', '덜컹거리다', 'rattle|rattled'],
  ['pendulum', 'the long weight that swings from side to side under a clock', '(시계의) 추'],
  ['weights', 'heavy pieces of metal that make an old clock go', '(시계를 움직이는) 추'],
  ['wound', 'past of "wind": turned the key that makes a clock go (say "waund")', '(태엽을) 감았다'],
  ['wind', 'to turn a key or handle to make a clock go (say "waind")', '(태엽을) 감다', 'wind it|winds things|winds|wind the chronometer|winding', 2],
  ['run down', '(of a clock) to slow down and stop because nobody winds it', '(태엽이 풀려) 멈추다'],
  ['a stone in its shoe', 'a way of saying it was not going evenly, like a person who limps', '절뚝거리는 듯한 (비유)'],
  ['wristwatch', 'a watch you wear on your arm', '손목시계'],

  /* --- things in the building --- */
  ['bolt', 'a metal bar that slides across to keep a door shut', '빗장', 'bolts'],
  ['bolted', 'shut with a bolt, a metal bar that slides across', '빗장을 지른', 'bolts the door|bolt the door'],
  ['bell-pull', 'a handle you pull to ring a bell inside a house', '초인종 당김줄'],
  ['fanlight', 'a small window above a door', '문 위의 채광창'],
  ['doorway', 'the opening where a door is', '문간, 출입구'],
  ['door frame', 'the wooden edge around a doorway', '문틀'],
  ['dust sheet', 'a large cloth put over furniture to keep the dust off', '먼지 막이 천', 'dust sheets'],
  ['sheet', 'a large piece of cloth (here, the cloth over the glass case)', '천, 덮개', 'sheets'],
  ['tuck', 'to push the edge of a cloth under something so it stays there', '(끝을) 밀어 넣다', 'tucked|tucks|tucked in'],
  ['draught', 'cold air that moves through a room (say "draft")', '외풍, 찬 바람'],
  ['will have it off', 'will pull it off', '벗겨 버릴 것이다'],
  ['caught on', 'held by something so that it cannot move', '~에 걸린'],
  ['brass', 'a bright yellow metal', '놋쇠, 황동'],
  ['iron', 'a hard, heavy, dark metal', '쇠, 철'],
  ['velvet', 'a soft, thick cloth', '벨벳'],
  ['plaster', 'the smooth, hard cover on an inside wall', '회반죽 (벽 마감재)'],
  ['cardboard', 'thick, stiff paper used for making boxes', '판지'],
  ['tar', 'a thick, black, sticky stuff used on ships and roads', '타르'],
  ['kettle', 'a pot for boiling water', '주전자'],
  ['tin', 'a metal box or can (British)', '깡통, 양철통'],
  ['cupboard', 'a small space with a door, for keeping things in', '찬장, 벽장'],
  ['damp', 'a little wet', '축축한'],
  ['flask', 'a bottle that keeps a drink hot', '보온병'],
  ['torch', 'a small electric light you hold in your hand (British)', '손전등'],
  ['torchlight', 'the light of a torch', '손전등 불빛'],
  ['keyhole', 'the hole in a lock where the key goes', '열쇠 구멍'],
  ['scratch', 'a thin mark made by something sharp', '긁힌 자국', 'scratches|scratched'],
  ['cord', 'a thick string', '끈'],
  ['whistle', 'a small pipe you blow to make a high, loud sound', '호루라기'],
  ['knitting', 'wool that somebody is making into clothes with two long needles', '뜨개질감'],
  ['cardigan', 'a knitted jacket that closes with buttons', '카디건'],
  ['rucksack', 'a bag you carry on your back (British)', '배낭'],
  ['parcel tape', 'strong brown sticky tape for closing boxes', '포장용 테이프'],
  ['taping up', 'closing with sticky tape', '테이프로 붙이는', 'taped'],
  ['purse', 'a small bag for money (British)', '(작은) 지갑'],
  ['biscuits', 'small flat dry cakes (British); cookies', '비스킷, 쿠키', 'biscuit'],
  ['packet', 'a small paper or plastic container that food is sold in', '봉지, 갑'],
  ['pile', 'a number of things lying one on top of another', '더미'],
  ['knots', 'ties made in rope or string', '매듭', 'knot'],
  ['anchor chain', 'the heavy chain that holds a ship\'s anchor', '닻을 매다는 쇠사슬'],
  ['diving helmet', 'a heavy metal helmet for working under the sea', '잠수 헬멧'],
  ['padlock', 'a lock that hangs on a metal loop', '맹꽁이자물쇠'],
  ['painted shut', 'stuck closed with old paint', '페인트로 굳어 안 열리는'],
  ['pinned', 'fixed there with a pin', '핀으로 꽂아 둔'],
  ['tied', 'fastened with string', '묶인'],
  ['torn', 'pulled open or into pieces (past of "tear")', '찢어진'],
  ['marked', 'with this word written on it', '~라고 표시된'],
  ['blank', 'with nothing written on it', '아무것도 안 쓰인'],
  ['faded', 'lost its colour with time', '(색이) 바랜'],
  ['faint', 'not strong; hard to see or hear', '희미한'],
  ['flash', 'a sudden bright light', '번쩍임'],
  ['the lot blows', 'all the fuses break (informal British)', '퓨즈가 전부 나가다'],

  /* --- people and how they talk --- */
  ['lad', 'a boy or young man (friendly British word)', '젊은이, 녀석'],
  ['fussy', 'caring too much about small things', '까다로운'],
  ['patient', 'able to wait, or to keep trying, for a long time', '참을성 있는'],
  ['unkind', 'not kind', '매정한, 불친절한'],
  ['pleased', 'happy about something', '기쁜, 만족스러운'],
  ['great-grandfather', 'the father of your grandfather or grandmother', '증조할아버지'],
  ['Cape Horn', 'the southern end of South America, famous for storms', '케이프 혼 (남미 최남단)'],
  ['lent', 'let somebody use it for a time (past of "lend")', '빌려주었다', 'lend|lends'],
  ['lit', 'made it burn (past of "light")', '불을 붙였다'],
  ['slid', 'moved smoothly (past of "slide")', '미끄러졌다', 'slides'],
  ['trotting', 'running slowly with short steps, as a horse does', '(말이) 종종걸음으로 달리는', 'trot'],
  ['stumbling', 'walking badly and almost falling', '비틀거리며 다니는', 'stumble|stumbled'],
  ['manage', 'to succeed in doing something difficult', '(어려운 일을) 해내다', 'managed'],
  ['suppose', 'to think that something is probably true', '~일 거라고 생각하다'],
  ['I expect', 'I think it is probably true', '아마 ~일 것이다'],
  ['notice', 'to see or hear something and know it is there', '알아차리다', 'noticing|noticed'],
  ['admire', 'to look at something with pleasure', '감탄하며 보다'],
  ['matters', 'is important', '중요하다', 'matter|mattered'],
  ['weighs', 'is this heavy', '무게가 ~이다'],
  ['arguing', 'not agreeing, and saying so', '말다툼하는', 'argue|argued'],
  ['frowns', 'makes an unhappy or puzzled face', '얼굴을 찌푸리다', 'frown|frowned'],
  ['nods', 'moves the head down and up to say yes', '고개를 끄덕이다', 'nod|nodded'],
  ['cheers', 'shouts happily', '환호하다'],
  ['underlines', 'draws a line under', '밑줄을 긋다'],
  ['folded', 'bent so that one part lies on another; (of hands) resting one on the other', '접은; (손을) 포갠', 'folds'],
  ['settling', 'moving a little and then lying still', '(움직이다) 자리 잡는'],
  ['swings open', 'opens, turning smoothly', '(문이) 휙 열리다', 'swings'],
  ['scrapes', 'makes a rough noise by moving across the floor', '끌리는 소리를 내다', 'scrape|scraped'],
  ['dies away', 'slowly becomes quiet', '(소리가) 잦아들다', 'died away'],
  ['goes on', 'continues', '계속하다'],
  ['carried on', 'continued', '계속했다'],
  ['tidy up', 'to put a place in order', '정리하다, 치우다'],
  ['felt my way', 'found where to go by touching things', '더듬어서 갔다'],
  ['out of breath', 'breathing fast after hurrying', '숨이 찬'],
  ['getting my breath back', 'resting until I could breathe easily again', '숨을 고르는'],
  ['keep quite still', 'do not move at all', '꼼짝 않고 있다', 'keep still|sit still'],
  ['mind', 'be careful of (British): "Mind the step!"', '~을 조심해', 'mind the|mind them', 2],
  ['shall', 'will (formal or old)', '~할 것이다 (격식체)'],
  ['ought to', 'should', '~해야 한다'],
  ['had better', 'should', '~하는 편이 좋다'],
  ['I should like', 'I would like (formal British)', '~하고 싶다 (격식체)', 'I should very much like'],
  ['allowed', 'able to do it because nobody says no', '허락된'],
  ['neither', 'not one and not the other', '둘 다 ~아닌'],
  ['whoever', 'the person who (we do not know who)', '~한 사람은 누구든'],
  ['afterwards', 'later; after that', '나중에, 그 후에'],
  ['aloud', 'in a voice that other people can hear', '소리 내어'],
  ['sideways', 'to the side, not straight down', '옆으로'],
  ['till', 'until', '~까지'],
  ['or so', 'about', '~쯤'],
  ['a bit', 'a little', '약간'],
  ['ages', 'a very long time (informal)', '아주 오랫동안'],
  ['as far as', 'to that place and no further', '~까지'],
  ['plenty of', 'more than enough', '충분한, 넉넉한'],
  ['no point', 'no good reason for doing it', '~해 봤자 소용없는'],
  ['a hand', 'help (informal)', '도움'],
  ['on her own', 'alone', '혼자서', 'on his own|on my own'],
  ['straight after', 'at once after', '~한 바로 다음에'],
  ['straight back', 'back at once', '곧장 돌아서'],
  ['straight off', 'off at once, with nothing to stop it', '그대로 스르르'],
  ['stone cold', 'completely cold', '완전히 식은'],
  ['a good ten minutes', 'at least ten minutes', '족히 10분'],
  ['it wasn\'t like her', 'she does not usually do that', '그녀답지 않았다'],
  ['does as it is told', 'does what somebody tells it to do', '시키는 대로 하다', 'does as it\'s told'],
  ['nearly finished me', 'almost killed me (he is joking)', '(농담) 날 잡을 뻔한'],
  ['break your neck', 'fall and hurt yourself badly', '(넘어져) 크게 다치다'],
  ['has no business being', 'should not be', '~에 있을 이유가 없다'],
  ['fit the times', 'agree with the times we know', '시간과 맞아떨어지다'],

  /* --- things you can click in the scenes; the first four also turn up in the story --- */
  ['gull', 'a large grey and white sea bird with a loud cry', '갈매기', 'gulls'],
  ['quay', 'a stone platform beside the water where boats tie up (say it like "key")', '부두'],
  ['puddle', 'a small pool of rain water on the ground', '웅덩이'],
  ['lighthouse', 'a tower by the sea with a strong light that guides ships', '등대', '', 0],
  ['mast', 'the tall pole on a boat that holds up the sails', '돛대', '', 0],
  ['bollard', 'a short, thick post on a quay; boats are tied to it', '배를 매는 말뚝', '', 0],
  ['lamp post', 'a tall post in the street with a light on top', '가로등', '', 0],
  ['chimney', 'the pipe on a roof that lets the smoke out', '굴뚝', '', 0],
  ['shutters', 'wooden covers that close over a window', '덧문', '', 0],
  ['cobbles', 'rounded stones that an old road is made of', '자갈 포장돌', '', 0],
  ['doorstep', 'the step in front of the door of a house', '문 앞 계단', '', 0],
  ['doormat', 'a small mat by the door for wiping your shoes', '현관 매트', '', 0],
  ['coat hook', 'a hook on the wall for hanging up a coat', '옷걸이 고리', '', 0],
  ['box file', 'a stiff box, like a thick book, for keeping papers in', '서류 보관 상자', '', 0],
  ['teapot', 'a pot with a handle and a spout, for making and pouring tea', '찻주전자', '', 0]
];
