/* Hover dictionary for "The Final Word".
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = a word the player has to find, or the name of a thing (never underlined in the text);
   flag 2 = underline the listed forms but not the bare headword */
window.GLOSS = [
  /* --- words the player has to find --- */
  ['live audience', 'the people who sit in a studio and watch a programme while it is being made', '현장 방청객', '', 0],
  ['interview', 'a talk in which one person asks the questions and another person answers them', '인터뷰', '', 0],
  ['subtitles', 'the words at the bottom of the screen that show what people are saying', '자막', '', 0],
  ['talent show', 'a programme in which people sing, dance or do tricks and try to win', '장기 자랑 프로그램, 오디션 프로그램', '', 0],
  ['episode', 'one part of a series on television', '(연속물의) 한 회', '', 0],
  ['newsreader', 'the person who reads the news on television or radio', '뉴스 진행자', '', 0],
  ['careless', 'not taking care; making mistakes because you are not thinking', '부주의한', '', 0],
  ['hopeless', 'with no hope; or, very bad at something', '희망이 없는; 형편없는', '', 0],
  ['useless', 'no use at all; not helping', '쓸모없는', '', 0],
  ['painless', 'not hurting at all', '아프지 않은', '', 0],
  ['harmless', 'not able to hurt anybody', '해가 없는', '', 0],
  ['endless', 'going on and on, with no end', '끝없는', '', 0],
  ['overheard', 'heard what somebody said when they were not talking to you (the past of "overhear")', '우연히 들은, 엿들은', '', 0],
  ['whisper', 'to speak very quietly, using only your breath', '속삭이다', '', 0],
  ['mutter', 'to speak in a low voice that is hard to hear, often because you are cross', '중얼거리다, 투덜거리다', '', 0],
  ['yell', 'to shout very loudly', '고함치다', '', 0],
  ['promise', 'to say that you will certainly do something; you can keep one or break one', '약속; 약속하다', '', 0],
  ['record', 'the best that anybody has ever done; a champion breaks one', '기록', '', 0],
  ['silence', 'no sound at all; you break it when you speak', '침묵, 고요', '', 0],
  ['drama', 'a serious story acted on television or in a theatre', '드라마, 극', '', 0],
  ['cartoon', 'a film made of drawings that move', '만화 영화', '', 0],
  ['pearl', 'a small round white jewel that grows inside a sea shell', '진주', '', 0],
  ['beard', 'the hair that grows on a man’s chin and cheeks', '턱수염', '', 0],
  ['the walls have ears', 'a saying: be careful what you say, because somebody may be listening', '벽에도 귀가 있다 (낮말은 새가 듣고 밤말은 쥐가 듣는다)', '', 0],
  ['attention', 'careful listening or watching; you "pay attention" to something', '주의, 집중', '', 0],

  /* --- things you can click --- */
  ['flight case', 'a strong box with metal corners, for carrying a show’s equipment', '장비 운반용 하드 케이스', '', 0],
  ['trolley', 'a small table on wheels', '(바퀴 달린) 카트, 손수레', '', 0],
  ['envelope', 'the paper cover that a letter goes in', '봉투', '', 0],

  /* --- the show --- */
  ['quiz', 'a game in which people try to answer questions', '퀴즈'],
  ['goes out', '(of a programme) is sent out to people’s televisions', '방송되다', 'go out|went out'],
  ['live', 'shown at the same moment as it happens, not recorded (it rhymes with "five")', '생방송으로; 생방송의'],
  ['final', 'the last game, which decides the winner; or, last', '결승전; 마지막의'],
  ['finalists', 'the two people who play in the final', '결승 진출자', 'finalist'],
  ['champion', 'the person who has beaten everybody else', '우승자, 챔피언'],
  ['runner', 'the youngest helper in a television studio, who carries messages and fetches things', '(방송국의) 심부름 담당 막내 스태프'],
  ['pupil', 'a child at school', '학생'],
  ['work experience', 'a short time that a school pupil spends in a real job, to see what it is like', '직업 체험'],
  ['fetch', 'to go and get something and bring it back', '가서 가져오다', 'fetches|fetching|fetched'],
  ['host', 'the person who presents a television show', '(프로그램) 진행자'],
  ['presented', 'been the host of', '진행해 왔다', 'presents'],
  ['programme', 'a show on television or radio', '(방송) 프로그램', 'programmes'],
  ['producer', 'the person in charge of making a television programme', '프로듀서, 제작 책임자'],
  ['gallery', 'here: the control room of a television studio, where the producer sits', '(여기서는) 방송국 부조정실'],
  ['studio', 'a room where television programmes are made', '스튜디오'],
  ['corridor', 'a long narrow way inside a building, with doors along it', '복도'],
  ['dressing room', 'a room where a performer gets ready', '분장실, 대기실'],
  ['green room', 'the room in a theatre or studio where performers wait', '출연자 대기실'],
  ['foyer', 'the big entrance hall of a theatre or studio (say "FOY-ay")', '로비'],
  ['set', 'here: the furniture and scenery that a show is filmed on', '(여기서는) 방송 세트, 무대 장치', 'the set', 2],
  ['board', 'here: the big screen where the game is shown', '(여기서는) 게임판, 문제판'],
  ['round', 'one part of a game or a quiz', '(게임의) 라운드, 판', 'the round|a round|one round|rounds|last round|round one|round two|round three|round four|round 1|round 2|round 3|round 4', 2],
  ['buzzers', 'buttons that make a loud sound when a player wants to answer', '부저, 버저', 'buzzer'],
  ['fingers on buzzers', 'what a quiz host says when the players must get ready to answer', '"버저에 손 올리세요" (퀴즈 진행자의 말)'],
  ['locked in', 'shut in a place with a lock, so that you cannot get out', '갇힌'],
  ['conundrum', 'a difficult puzzle; on this show, nine mixed-up letters that make one word', '난제, 수수께끼; (이 쇼에서는) 철자 맞추기 문제'],
  ['mixed-up', 'put in the wrong order', '뒤섞인'],
  ['vowels', 'the letters A, E, I, O and U', '모음', 'vowel'],
  ['consonants', 'all the letters that are not vowels', '자음', 'consonant'],
  ['odd one out', 'the one that is different from all the others', '나머지와 다른 하나', 'odd ones out'],
  ['odd', 'here: different from the others', '(여기서는) 나머지와 다른'],
  ['belong', 'to be in the right place; to be one of a group', '속하다, 어울리다', 'belongs'],
  ['in a row', 'one after another, with nothing in between; or, side by side in a line', '연달아; 한 줄로'],
  ['running', 'here: one after another, without a break', '(여기서는) 연속으로', 'Fridays running', 2],
  ['call sheet', 'a list that tells everybody on a show where to be, and when', '촬영 일정표'],
  ['pinboard', 'a board on a wall where papers are fixed with pins', '게시판'],
  ['cutting', 'a piece cut out of a newspaper', '신문 스크랩'],
  ['by hand', 'carried by a person, not sent', '인편으로, 직접'],
  ['do not disturb', 'do not come in and do not make a noise', '방해하지 마시오'],
  ['on air', 'being sent out on television or radio at this moment', '방송 중'],
  ['kindly', 'an old-fashioned, very polite word for "please"', '부디, 아무쪼록 (please의 예스럽고 정중한 말)'],

  /* --- people and what they do --- */
  ['clunk', 'the short, heavy sound of a lock shutting', '철컹 하는 소리'],
  ['ceiling', 'the top of a room, above your head', '천장'],
  ['shuts', 'closes', '닫다', 'shut'],
  ['knock', 'to hit a door with your hand so that people know you are there', '노크하다', 'knocks|knocking'],
  ['polite', 'having good manners', '예의 바른'],
  ['manners', 'the way you behave with other people', '예의, 매너'],
  ['still water', 'water with no bubbles in it', '탄산이 없는 물'],
  ['bubbles', 'small balls of gas in a drink', '기포, 탄산'],
  ['mirror', 'a piece of glass in which you can see yourself', '거울'],
  ['out loud', 'so that people can hear; not silently', '소리 내어'],
  ['bless her', 'what people say about somebody they are fond of', '고맙기도 하지 (애정을 담아 하는 말)'],
  ['a beauty', 'a very good one', '아주 멋진 것'],
  ['run along', 'go away now (said to a child)', '어서 가 보렴'],
  ['bursts', 'breaks open suddenly, like a balloon', '터지다'],
  ['hardly', 'almost not', '거의 ~않다'],
  ['trick', 'a clever way of doing something that other people cannot see', '속임수, 요령'],
  ['tuned', 'made a piano play the right notes', '(피아노를) 조율했다'],
  ['note', 'here: one sound in music', '(여기서는) 음', 'wrong note', 2],
  ['nervous', 'a little afraid', '긴장한'],
  ['strangely', 'in a way that is not usual', '이상하게도'],
  ['pleased', 'happy about something', '기뻐하는, 만족한'],
  ['cardigan', 'a woollen jacket with buttons down the front', '카디건'],
  ['swings', 'moves round on its hinges', '(문이) 휙 열리다'],
  ['rhyme', 'to end with the same sound, like "cat" and "hat"', '운이 맞다', 'rhymes'],
  ['adjective', 'a word that tells you what a person or a thing is like: big, red, happy', '형용사', 'adjectives'],
  ['verb', 'a word for something you do: run, eat, think', '동사', 'verbs'],
  ['aloud', 'so that people can hear', '소리 내어'],
  ['stand in for', 'be used in place of', '~을 대신하다'],

  /* --- the gallery --- */
  ['soundproof', 'made so that sound cannot get through', '방음의'],
  ['headset', 'headphones with a small microphone', '헤드셋'],
  ['monitor', 'a screen that shows what a camera sees', '모니터 (화면)', 'monitors'],
  ['log', 'the written record of everything that happens', '기록, 일지'],
  ['memo', 'a short note to somebody you work with', '(사내) 메모', 'memos'],
  ['pinned', 'fixed to a board with a pin', '(핀으로) 꽂아 놓은'],
  ['typed', 'wrote with a keyboard', '(자판으로) 쳤다', 'type them'],
  ['rehearsal', 'a practice before the real show', '리허설, 예행연습'],
  ['technical rehearsal', 'a practice for the cameras and the machines, not for the people', '기술 리허설'],
  ['practice set', 'a set of questions that is only for practising, never for the real show', '연습용 문제 세트'],
  ['made ready', 'prepared, so that it could start', '준비해 두었다'],
  ['set it going', 'started it', '작동시켰다'],
  ['sealed', 'closed so that nobody can open it without breaking something', '봉인된, 봉한'],
  ['by accident', 'without meaning to', '우연히'],
  ['under your breath', 'very quietly, so that nobody else can hear', '들릴 듯 말 듯, 혼잣말로'],
  ['deals', 'gives out cards or letters to a player', '(카드·글자를) 나눠 주다', 'dealt|deal'],
  ['face down', 'with the front side hidden', '앞면이 아래로 가게 (뒤집어서)'],
  ['turn over', 'to move so that the other side shows', '뒤집히다', 'turned over|turns over'],
  ['lips', 'the two soft edges of your mouth', '입술'],
  ['lipstick', 'colour that people put on their lips', '립스틱'],
  ['backwards', 'with the last part first, like writing seen in a mirror', '거꾸로'],
  ['look into it', 'find out more about it', '알아보다, 조사해 보다'],
  ['good television', 'fun for people to watch', '방송에 내보내기 좋은 (사람·장면)'],
  ['viewers', 'the people who watch a television programme', '시청자'],
  ['I would bet my job on it', 'I am completely sure of it', '내 자리를 걸고 장담한다'],
  ['car park', 'a place where cars are left', '주차장'],
  ['ribbon', 'a long thin piece of cloth', '리본, 끈'],
  ['crisps', 'thin slices of fried potato, sold in a bag', '감자 칩'],
  ['colour bars', 'the stripes of colour that a screen shows when it has no picture', '(화면 조정용) 컬러 바'],
  ['switched off', 'not working, because somebody has turned it off', '꺼진'],
  ['crossword', 'a word puzzle in a square of black and white boxes', '십자말풀이'],
  ['worth', 'good enough to spend time on', '~할 만한 가치가 있는'],

  /* --- the studio --- */
  ['booth', 'a very small room for one person', '부스, 작은 칸막이 방', 'booths'],
  ['board desk', 'the desk beside the set from which the game board is worked', '(세트 옆) 게임판 조작 데스크'],
  ['stool', 'a seat with no back', '등받이 없는 의자'],
  ['wax', 'the stuff that candles are made of. Warm, it can be pressed onto an envelope to shut it', '밀랍 (봉인용 왁스)'],
  ['cream', 'here: a pale yellow-white colour', '(여기서는) 크림색'],
  ['pressed', 'pushed', '눌렀다; 눌러 찍힌', 'press|presses'],
  ['stuck', 'fixed on with glue', '붙여 놓았다'],
  ['label', 'a small piece of paper that says something about the thing it is on', '라벨, 딱지'],
  ['owners', 'the people that things belong to', '주인'],
  ['stranger', 'somebody who does not belong to the group', '낯선 사람, 외부인'],
  ['glue', 'sticky stuff for mending broken things', '접착제, 풀'],
  ['channels', 'television stations', '(TV) 채널'],
  ['spelt', 'written with these letters', '철자가 ~로 쓰인', 'spell'],
  ['side by side', 'next to each other', '나란히'],
  ['one at a time', 'not together: first one, then the next', '한 번에 하나씩'],
  ['sigh', 'a long, soft breath out', '한숨 (같은 소리)'],
  ['loudspeakers', 'the parts of a sound system that the sound comes out of', '스피커, 확성기', 'loudspeaker'],
  ['capital letters', 'big letters: A, B, C, not a, b, c', '대문자'],
  ['raised her voice', 'spoken loudly because she was angry', '언성을 높였다'],
  ['steal', 'to take something that is not yours', '훔치다'],
  ['folds up', 'bends paper so that it becomes smaller', '접다', 'folds'],
  ['rather', 'a little; more than you might think', '꽤, 좀'],
  ['noon', 'twelve o’clock in the middle of the day', '정오'],
  ['photographs', 'pictures taken with a camera', '사진'],
  ['reason', 'why something is so', '이유'],
  ['crossly', 'in a way that shows you are a little angry', '짜증스럽게'],
  ['argue', 'to say that you do not agree', '반박하다, 따지다'],

  /* --- on air --- */
  ['series', 'a set of programmes with the same name, shown week after week', '시리즈, 시즌'],
  ['points', 'here: marks that you win in a game', '(여기서는) 점수', 'seventy points', 2],
  ['tiles', 'here: small flat squares, each with one letter on it', '(여기서는) 글자 타일'],
  ['clap', 'to hit your hands together to show that you like something', '박수 치다'],
  ['understood', 'the past of "understand"', '이해했다'],
  ['microphone', 'a thing you speak into, which makes your voice louder', '마이크'],
  ['a good deal longer', 'much longer', '훨씬 더 오래'],
  ['afterwards', 'later; after that', '그 후에'],
  ['explain', 'to make something clear by saying how or why', '설명하다'],
  ['at last', 'in the end, after a long time', '마침내'],
  ['crew', 'the people who work together to make a programme', '제작진, 스태프'],

  /* --- words about words --- */
  ['opposite', 'as different as possible: hot is the opposite of cold', '반대말, 반대'],
  ['recorded', 'made earlier and kept, not happening now', '녹화된, 녹음된'],
  ['past forms', 'the shapes of a verb that you use for yesterday: went, took, saw', '과거형', 'past form'],
  ['in the past', 'about a time before now', '과거의 (과거형으로 된)'],
  ['ending', 'the last letters of a word', '(낱말의) 끝부분'],
  ['joined', 'put together', '이어 붙인, 합쳐진'],
  ['for ever', 'for all time', '영원히'],
  ['not even close', 'a long way from the right answer', '근처에도 못 간'],
  ['unlucky', 'not lucky', '운이 없는'],
  ['impressed', 'thinking that something is very good', '감명받은'],
  ['plenty', 'more than enough', '충분히 많음'],
  ['shares', 'has together with something else', '함께 쓰다, 공유하다'],
  ['doorway', 'the opening that a door closes', '문간, 출입구'],
  ['woken up', 'stopped sleeping', '깨어났다']
];

