/* Hover dictionary for "Wrong Number".
   What goes in: a word or phrase a Korean middle-school student has probably not met, and British or
   idiomatic uses of easy words. Check new story text with: python wordlist.py cipher/wrong
   [headword, meaning in easy English, Korean, other forms to match (a|b|c), flag]
   flag 0 = never underlined in the text (the name of a thing in a scene, or a word the player has to find);
   flag 2 = underline the listed forms but not the bare headword */
window.GLOSS = [
  /* --- the words the player has to find (flag 0: they go into the notebook when they are found) --- */
  ['strongroom', 'a room with thick walls and a heavy door, where a shop or a bank locks up its gold and money', '금고실 (귀중품을 넣어 두는 방)', '', 0],
  ['behind', 'at the back of', '~의 뒤에', '', 0],
  ['itself', 'by its own power, with nobody touching it; alone, with nothing else', '저절로, 스스로; 그것만', '', 0],
  ['twelfth', 'number 12 in a line: the one that comes after the eleventh', '열두 번째(의)', '', 0],
  ['midnight', 'twelve o\'clock at night', '자정, 밤 12시', '', 0],
  ['cheap', 'costing only a little money', '값이 싼', '', 0],
  ['secret', 'known to only a few people, and kept from everybody else', '비밀의; 비밀', '', 0],
  ['window', 'the glass at the front of a shop, or in the wall of a house', '창문, (가게의) 진열창', '', 0],
  ['notice', 'a paper with something written on it, put up where people will read it', '공고문, 안내문', '', 0],
  ['worth', 'having a value of (so much money)', '~의 가치가 있는', '', 0],
  ['jeweller', 'a person who sells and mends rings, watches and necklaces (American English: jeweler)', '보석상', '', 0],
  ['stranger', 'a person you have never met and do not know', '낯선 사람', '', 0],
  ['Saturday', 'the day that comes after Friday', '토요일', '', 0],
  ['seldom', 'not often', '드물게, 좀처럼 ~하지 않는', '', 0],
  ['valuable', 'worth a lot of money', '값진, 귀중한', '', 0],
  ['opposite', 'on the other side from; facing', '~의 맞은편에', '', 0],
  ['enough', 'as much as is needed', '충분한', '', 0],
  ['exactly', 'no more and no less; just', '정확히, 딱', '', 0],
  ['expect', 'to think that something is probably true (British English: "I expect you know")', '(아마) ~일 거라고 생각하다', '', 0],
  ['ready', 'able to be used at once', '준비가 된', '', 0],
  ['handle', 'the part of a door or a tool that you hold in your hand', '손잡이', '', 0],
  ['heavy', 'weighing a lot; hard to lift or to move', '무거운', '', 0],
  ['careful', 'thinking about what you are doing, so that nothing goes wrong', '조심하는, 주의 깊은', '', 0],
  ['minute', 'sixty seconds; a very short time', '분; 잠깐', '', 0],
  ['pearl', 'a small, round, white jewel that grows inside a shellfish', '진주', '', 0],
  ['clasp', 'the small metal part that fastens a necklace or a bracelet', '(목걸이·팔찌의) 잠금 고리', '', 0],
  ['chain', 'a line of small metal rings joined together; a necklace made like this', '사슬, 목걸이 줄', '', 0],

  /* --- names of things in the scenes (flag 0) --- */
  ['motorbike', 'a bicycle with an engine', '오토바이', '', 0],
  ['camera', 'here: a small machine over a door that shows the street on a screen inside', '(여기서는) 감시 카메라', '', 0],
  ['sign', 'a board with a name or a picture on it, outside a shop', '간판', '', 0],
  ['street lamp', 'a tall lamp at the side of a street', '가로등', '', 0],
  ['timetable', 'a list of the times when buses or trains leave', '시간표', '', 0],
  ['lock', 'the part of a door that keeps it shut until the right key (or the right word) is used', '자물쇠', '', 0],
  ['clock', 'a thing on a wall or a shelf that shows the time', '시계 (벽시계·탁상시계)', '', 0],
  ['pendulum', 'the weight on a long rod that swings from side to side inside a tall clock', '(시계의) 추, 진자', '', 0],
  ['velvet', 'a thick, soft cloth that jewellers lay rings on', '벨벳 (부드럽고 두꺼운 천)', '', 0],
  ['tray', 'a flat, shallow box or board for carrying or showing small things', '쟁반, (진열용) 받침판', '', 0],
  ['helmet', 'a hard hat that keeps your head safe on a motorbike', '헬멧', '', 0],
  ['workbench', 'a strong table for working at with tools', '작업대', '', 0],

  /* --- the street and the telephone --- */
  ['phone box', 'a small glass shelter in the street with a public telephone in it', '공중전화 부스', 'phone boxes'],
  ['wrong number', 'a telephone call that reaches the wrong person by mistake', '잘못 걸린 전화'],
  ['has been dead', 'here: has not been working, because it has no power left', '(여기서는) 전원이 꺼져 있다'],
  ['fish bar', 'a shop that sells fried fish and chips', '피시 앤드 칩스 가게'],
  ['receiver', 'the part of a telephone that you hold to your ear and your mouth', '수화기'],
  ['hisses', 'makes a long "sss" sound', '쉬익 소리를 내다'],
  ['frying pan', 'a flat pan for cooking food in hot oil', '프라이팬'],
  ['deaf', 'not able to hear', '귀가 들리지 않는'],
  ['steel', 'a very strong, hard metal', '강철'],
  ['shuts', 'closes', '닫히다, 닫다', 'shut'],
  ['suppose', 'to think that something is probably true', '~라고 짐작하다'],
  ['wires', 'long thin pieces of metal that carry electricity or telephone calls', '전선', 'wire'],
  ['nearly', 'almost', '거의'],
  ['ring the police', 'telephone the police (British English)', '경찰에 전화하다'],
  ['fire brigade', 'the people whose job is to put out fires and to get people out of dangerous places (British English)', '소방대'],
  ['quicker', 'faster', '더 빠른'],
  ['nod', 'to move your head down and up, to say yes', '고개를 끄덕이다', 'nods|nodded'],
  ['telephone exchange', 'the place, full of machines, that joins one telephone line to another', '전화 교환국'],
  ['automatic', 'done by a machine, with no person', '자동의'],
  ['private', 'for one person only, not for everybody', '개인 전용의'],
  ['public', 'for everybody to use', '공공의, 누구나 쓰는'],
  ['key in', 'to type letters or numbers on the keys of a machine', '(자판으로) 입력하다'],
  ['10p', 'ten pence: a small British coin', '10펜스 (영국 동전)', 'ten pence'],
  ['swallows', 'takes something in and does not give it back, as you do with food', '삼키다'],
  ['bus fare', 'the money that you pay to go by bus', '버스 요금'],
  ['credit', 'here: money that you have already paid for a telephone call', '(여기서는) 통화 요금 잔액'],
  ['gives up', 'stops trying', '포기하다', 'give up|gave up'],
  ['letter lock', 'a lock that opens with a word, not with a key', '글자 자물쇠'],
  ['mend', 'to make a broken thing whole again', '고치다, 수선하다', 'mended|mending|mends'],
  ['customers', 'the people who buy things in a shop', '손님, 고객', 'customer'],
  ['holes', 'empty places where something is missing', '구멍, 빈 곳', 'hole'],

  /* --- the notice in the window --- */
  ['letter box', 'the narrow hole in a door that letters are pushed through', '(문에 난) 우편물 투입구'],
  ['frightens', 'makes somebody afraid', '겁을 주다'],
  ['brass', 'a yellow metal that looks a little like gold', '놋쇠, 황동'],
  ['bench', 'here: a strong table for working at', '(여기서는) 작업대', 'workbench'],
  ['expensive', 'costing a lot of money', '값이 비싼'],
  ['repair', 'the mending of a broken thing', '수리'],
  ['burglars', 'people who break into houses and shops to steal things', '(침입) 도둑', 'burglar'],
  ['are welcome to', 'may do it freely: nobody will stop them', '~해도 좋다'],
  ['keyhole', 'the hole in a lock where the key goes', '열쇠 구멍'],
  ['ought to be', 'should be', '~여야 한다'],
  ['parked', 'left in the street (of a car or a motorbike)', '주차된'],
  ['scratches', 'thin lines made on something by a sharp point', '긁힌 자국'],
  ['for once', 'this one time (it does not usually happen)', '웬일로, 이번만은'],
  ['now and then', 'sometimes, but not often', '가끔'],
  ['a great many', 'very many', '아주 많은'],
  ['press', 'to push with your finger', '누르다', 'pressed'],
  ['sweets', 'small sweet things to eat (American English: candy)', '사탕, 군것질거리'],
  ['responsible', 'to be blamed if something goes wrong', '책임이 있는'],
  ['goes blank', 'becomes empty, with nothing on it', '(화면이) 텅 비다'],
  ['empties', 'makes itself empty', '비우다, 텅 비다'],
  ['appears', 'comes to where you can see it', '나타나다'],
  ['belongs', 'has its right place', '제자리이다, 속하다'],
  ['save itself for', 'to keep itself for one person only', '~만을 위해 아껴 두다'],
  ['doubled', 'written twice', '두 번 겹쳐 쓴'],
  ['pence', 'small British money: a hundred pence make one pound', '펜스 (영국 화폐 단위)'],
  ['caller', 'the person who is telephoning', '전화를 건 사람'],
  ['at least', 'if nothing else; that much is good', '적어도, 그나마'],
  ['stuck', 'fixed there with glue or sticky tape', '붙어 있는'],
  ['a great deal', 'very much', '아주 많이'],
  ['pin', 'here: the sharp metal point that fastens a brooch to your clothes', '(여기서는) 브로치의 핀'],

  /* --- the shop --- */
  ['ticking', 'the small, regular sound that a clock makes', '(시계의) 똑딱 소리'],
  ['trap', 'a trick to catch somebody who is not careful', '함정'],
  ['nothing on earth', 'nothing at all (a strong way of saying it)', '세상 그 무엇도'],
  ['shade', 'here: the cover over a lamp', '(여기서는) 전등갓'],
  ['burning', 'here: giving light', '(여기서는) 불이 켜져 있는'],
  ['cream-coloured', 'yellowish white', '크림색의'],
  ['clatter', 'to make the noise of hard things knocking together quickly', '덜거덕거리다', 'clatters'],
  ['strip', 'a long narrow piece', '길고 가는 조각'],
  ['counter', 'the long table in a shop where you are served', '(가게의) 계산대'],
  ['capital letters', 'the big form of letters: A, B, C', '대문자'],
  ['frame', 'the wooden edge round a picture or a list on a wall', '액자, 틀'],
  ['argue', 'to say different things and not agree', '다투다, 의견이 엇갈리다'],
  ['grandfather clock', 'a very tall clock that stands on the floor', '대형 괘종시계'],
  ['swinging', 'moving from side to side while hanging', '흔들리는', 'swings'],
  ['try to picture', 'try to see in your mind', '머릿속에 그려 보다'],
  ['charges', 'asks people to pay', '(요금을) 받다, 청구하다'],
  ['row', 'a line of things side by side', '줄, 열', 'a row of|three rows', 2],
  ['allows', 'lets you have or do', '허락하다, 허용하다', 'allowed'],
  ['tries', 'here: chances to do something', '(여기서는) 시도 횟수, 기회'],
  ['marked', 'here: shown to be right or wrong', '(여기서는) 표시했다'],
  ['crossed off', 'taken off a list', '(목록에서) 지워진'],
  ['slides', 'moves smoothly along', '미끄러지듯 움직이다'],
  ['spare', 'extra, and kept in case it is needed', '여분의, 예비의'],
  ['plate', 'here: a small flat piece of metal with words on it', '(여기서는) 금속 명판', 'little plate', 2],
  ['accepted', 'taken as right, and allowed', '받아들여진, 승인된'],
  ['lit', 'with a light on', '불이 켜진'],
  ['blink', 'to go off and on again very quickly', '깜박이다'],
  ['stand well back', 'stand a good way away', '멀찍이 물러서다'],
  ['waste', 'to use something badly, so that it is lost', '낭비하다'],
  ['handwriting', 'the letters that a person writes by hand', '손글씨'],
  ['in order', 'one after another, from the first to the last', '차례대로, 순서대로'],
  ['leather', 'the skin of an animal, made into shoes, bags and straps', '가죽'],
  ['fitted', 'put on, in exactly the right place', '맞춰 끼운'],
  ['necklace', 'a chain or a string of jewels that you wear round your neck', '목걸이'],
  ['replaced', 'changed for a new one', '교체한'],
  ['oiled', 'given a little oil, so that the parts move easily', '기름칠을 한'],
  ['advice', 'what somebody tells you that you ought to do', '조언'],

  /* --- midnight --- */
  ['thief', 'a person who steals things', '도둑'],
  ['prints', 'puts words on paper (said of a machine)', '인쇄하다', 'printing'],
  ['sergeant', 'a police officer, one step above an ordinary officer', '경사 (경찰 계급)'],
  ['earned', 'got it by working for it', '(노력해서) 얻어 낸'],
  ['lift', 'the small moving room that carries people up and down inside a building (American English: elevator)', '엘리베이터', 'a lift', 2],
  ['bare bulb', 'an electric light with no shade round it', '갓 없는 전구'],
  ['tin box', 'a box made of thin metal', '양철 상자'],
  ['leather jacket', 'a short coat made of leather', '가죽 재킷'],
  ['carrier bag', 'a plastic bag from a shop (British English)', '비닐 쇼핑백'],
  ['argument', 'an angry talk between people who do not agree', '말다툼'],
  ['neat', 'tidy, with everything in its place', '단정한'],
  ['waistcoat', 'a jacket with no sleeves, worn over a shirt (American English: vest)', '조끼'],
  ['took your time', 'were slow; did not hurry', '꾸물거렸다, 서두르지 않았다'],
  ['a quarter of an hour', 'fifteen minutes', '15분'],
  ['gap', 'an empty space where something ought to be', '빈칸, 틈'],
  ['gently', 'softly, without pressing hard', '살살, 부드럽게'],
  ['breathing down your neck', 'standing very close behind you and watching everything that you do', '바로 뒤에서 지켜보며 재촉하는'],
  ['the keys stick', 'the keys do not go down, or do not come up again, as they should', '자판이 뻑뻑해서 잘 안 눌린다'],
  ['engagement rings', 'rings that people give when they promise to marry', '약혼반지'],
  ['strike', 'here: (of a clock) to ring, to tell the hour', '(여기서는) (시계가) 종을 쳐서 시각을 알리다'],
  ['wanting a word with', 'wanting to talk seriously to', '~와 (진지하게) 얘기 좀 하려 하다'],
  ['hear him out', 'listen until he has finished', '끝까지 들어 주다'],
  ['dust', 'dry dirt, like powder, that lies on things nobody has touched', '먼지'],
  ['harmless', 'not able to hurt anybody; perfectly ordinary', '해가 없는, 평범해 보이는'],
  ['textphone', 'a telephone with keys and a screen, for people who cannot hear', '문자 전화기 (청각 장애인용)', '', 0]
];
